### ISSUE TITLE
There is no "Web" in NFC

### ISSUE THREAD

**Issue by cyberphone** [w3c-cg/web-nfc#100]
NFC is a communication channel where none of the parties can determine if the other party is a Web application or not.

This makes the Web NFC security model somewhat less useful as well as limiting the kind of applications that can utilize the concept.

Feel free closing this issue now, I only provided this input "for the record".

**Comment by anssiko** [comment]
The Web NFC API uses the Web's security model. In practice this means the API is tightly scoped, and not all of the NFC functionality of the underlying platform is exposed to the Web.

In particular, there is no such thing as the "Web NFC security model". There is just the Web's security model implemented by browsers.
