### ISSUE TITLE
Rename data to entries

### ISSUE THREAD

**Issue by kenchris** [w3c-cg/web-nfc#103]
data in nfc.push({ data: [{ data: { name: "hey" }}]}) is confusing.

'entries' is used a lot in existing DOM APIs.

 nfc.push({ entries: [{ data: { name: "hey" }}]})

is much nicer

**Comment by alexshalamov** [comment]
@kenchris wouldn't it better to align with spec / NFC terms and use `records`?

`nfc.push({ records: [{ data: { name: "hey" }}]})`

I can make PR + align chromium impl

**Comment by kenchris** [comment]
Yeah sure, let's do it
