### ISSUE TITLE
Simplify 'URL pattern' concept for watch operation

### ISSUE THREAD

**Issue by alexshalamov** [w3c-cg/web-nfc#124]
We can simplify URL pattern concept, while maintaining same functionality.

- Wildcard would be only allowed for path.
- Protocol is fixed to https or any other allowed scheme.
- Domain matches domain and all subdomains, specifying subdomain will reduce scope to subdomain level.

Therefore, URL pattern would be a valid URL that can be tokenized / split to components with existing URL parsers.

**Comment by alexshalamov** [comment]
@kenchris @zolkis @anssiko what do you think?

**Comment by kenchris** [comment]
Let's do that then.

**Comment by zolkis** [comment]
I've been thinking the same, and very much support this. +1
