### ISSUE TITLE
Type5 support in web NFC APIs

### ISSUE THREAD

**Issue by collador** [w3c-cg/web-nfc#133]
The WEB NFC APIs specs do not explicitly mention the type5.
The Introduction talks about type1 to type4.
The type5 is now officially part of the NFC forum specs.
Given the current implementation in chromium the Web NFC APIs work fine on Android devices with Type5 tags. Indeed the implementation is tech agnostic (using NDEF APIs from Android).
Moreover, beginning of june Apple mentioned that iOs 11 will open NFC APis (In a first step to read NDEF messages). Actually iOs 11 in beta version do support the type5, 
I do not know if Safari 'll support the WebNFC Apis,  but type 5 is definitively an important actor of the NFC ecosystem (providing, for instance better performances in read range).
I think that it should now be added to these specs. It would be a bug to ignore the type5

**Comment by kenchris** [comment]
Yes, we should definitely support this.
