### ISSUE TITLE
Clarify scope matching

### ISSUE THREAD

**Issue by zolkis** [w3c-cg/web-nfc#15]
The exact meaning of scope, pattern, and the matching algorithm to origins need to be reviewed with the [Web Application Security WG](http://www.w3.org/2011/webappsec/).
This concerns both the [security and privacy doc](http://w3c.github.io/web-nfc/security-privacy.html#implementation-details) and the [API](http://w3c.github.io/web-nfc/#the-within-scope-algorithm).

**Comment by kenchris** [comment]
Can we close, we dont really use this anymore?
