### ISSUE TITLE
Do not use "script execution environment"

### ISSUE THREAD

**Issue by domenic** [w3c-cg/web-nfc#156]
"script execution environment" is not a well-defined term. The spec links to https://html.spec.whatwg.org/#script-execution-environment which does not exist. It then seems to try to define it itself, but in a way that doesn't actually say what it is.

I'm not sure what the point of this term is, but it seems to be only used in the non-normative security policies section, plus once redundantly elsehwere ("Each Window object connected to the script execution environment" can just be "Each Window object") so hopefully it can be removed.

**Comment by littledan** [comment]
The NFC global state has to be associated with something or other. Would it make sense to hang it off the environment settings object?

**Comment by kenchris** [comment]
Yes, we are moving towards using constructors and getting rid of the NFC interface, so we need somewhere to store the internal slots
