### ISSUE TITLE
navigator.nfc undefined

### ISSUE THREAD

**Issue by jdiegosierra** [w3c-cg/web-nfc#161]
When I test my phone in this web https://whatwebcando.today/nfc.html I'ts okey.
However when I use my own web navigator.nfc is undefined. 

![image](https://user-images.githubusercontent.com/27728978/46872858-94cf4400-ce35-11e8-9b97-c55449f6978d.png)

**Comment by rohmanhm** [comment]
What is your phone? And what browser do you use?

**Comment by anssiko** [comment]
As with most powerful capabilities, only content served over https is allowed to access Web NFC API. If you are using a local development environment, you may be running into this issue.

For the record, this is specified in:
https://w3c.github.io/web-nfc/#extensions-to-the-navigator-interface
https://w3c.github.io/web-nfc/#the-nfc-interface

`[SecureContext]` is to say the API is exposed only within a secure context that is spec-speak for https.

Also noted in the security policies section, see the first bullet at:
https://w3c.github.io/web-nfc/#security-policies

Hope this helps, and good luck with your further Web NFC experiments! I'm closing this issue. Any feature requests or spec bugs, please open a new issue.

**Comment by anujwebkul** [comment]
@anssiko 
I am using chrome version 79.. but still navigator.nfc undefined and I have enabled the webnfc flag as well.

**Comment by beaufortfrancois** [comment]
@anujwebkul `navigator.nfc` is not a thing anymore in Web NFC. See https://w3c.github.io/web-nfc/#examples for many examples on how to play with Web NFC. Hopefully you'll have fun!

**Comment by anujwebkul** [comment]
@beaufortfrancois but when I am using reader.scan(); then it gives the below error.
DOMException: WebNFC feature is unavailable.

**Comment by beaufortfrancois** [comment]
According to https://cs.chromium.org/chromium/src/third_party/blink/renderer/modules/nfc/nfc_proxy.cc?type=cs&sq=package:chromium&g=0&l=201, it looks like NFC support is not available on your device. Which Android device do you have?

**Comment by riju** [comment]
@anujwebkul : Can you try on [Chrome canary](https://play.google.com/store/apps/details?id=com.chrome.canary&hl=en) and let us know if the issue still persists ?

**Comment by anujwebkul** [comment]
It's working on [chrome beta](https://play.google.com/store/apps/details?id=com.chrome.beta&hl=en) like a charm, Thanks :)

**Comment by beaufortfrancois** [comment]
But not Chrome canary?

**Comment by anujwebkul** [comment]
@beaufortfrancois No.

**Comment by leonhsl** [comment]
I tried the canary `81.0.4031.0` and `reader.scan()` works well there.

Is there a chance that you forgot to turn on the flag `WebNFC` via `chrome://flags`? @anujwebkul
