### ISSUE TITLE
Specify encoding/decoding algorithms

### ISSUE THREAD

**Issue by zolkis** [w3c-cg/web-nfc#187]
As discussed in #186, we need to fix the way encoding/decoding is currently specified.

**Comment by annevk** [comment]
It seems like it'd be ideal to return a Uint8Array and allow passing a Uint8Array and recommend the Encoding API for any necessary conversions.

**Comment by kenchris** [comment]
Please check comments here: https://github.com/w3c/web-nfc/pull/186
