### ISSUE TITLE
Byte and byte sequence vs octet/octets

### ISSUE THREAD

**Issue by kenchris** [w3c-cg/web-nfc#194]
Hi @annevk and @domenic 

The current spec uses octets a lot (as written by @zolkis) but I notice that INFRA uses byte and byte sequences. Any recommendation here?

**Comment by kenchris** [comment]
It also uses the term "opaque octet stream" - what do you mean with that @zolkis ?

**Comment by annevk** [comment]
I prefer byte as that's the more commonly used word. Even though you technically can have architectures where a byte is not an octet, I don't think that's worth worrying about as any such architecture would not be compatible with the web platform and need special care anyway.
