### ISSUE TITLE
There's no such thing as current browsing context. A browsing context also has no URL path.

### ISSUE THREAD

**Issue by kenchris** [w3c-cg/web-nfc#200]
There's no such thing as current browsing context. A browsing context also has no URL path.

**Comment by kenchris** [comment]
Comment from @annevk:

> So you need to figure out what object you want the URL from and find a way from where you are now to there. I don't really see how browsing contexts relate here since they don't carry URLs.

**Comment by kenchris** [comment]
So we have the `environment settings object` which has a https://html.spec.whatwg.org/multipage/webappapis.html#responsible-document

Which has location which has a path.

@zolkis I assume this is what we are after?

**Comment by kenchris** [comment]
But then there are comments like 
![image](https://user-images.githubusercontent.com/1101339/53175152-aeef0f00-35eb-11e9-9fa2-5dc303271afa.png)

So I guess what we need is `the environment settings object's responsible document's URL path`

Would that be correct @annevk ?

**Comment by annevk** [comment]
You need a particular environment settings object (relevant or current I suspect), though you could also use a particular global object. "URL path" is also nothing, strictly speaking. You need a URL's path.
