### ISSUE TITLE
Security Review: push() method:  The “platform specific timeout” should be bounded

### ISSUE THREAD

**Issue by kenchris** [w3c-cg/web-nfc#208]
The “platform specific timeout” should be bounded so the user doesn’t accidentally write to the wrong device many minutes later, potentially leaking data.

**Comment by leonhsl** [comment]
https://github.com/w3c/web-nfc/pull/428/ already removed the timeout from `NDEFPushOptions`.

**Comment by beaufortfrancois** [comment]
@kenchris Can we close this one?

**Comment by beaufortfrancois** [comment]
(gentle ping)
