### ISSUE TITLE
Is anyone using WebNFC successfully?

### ISSUE THREAD

**Issue by M600LT** [w3c-cg/web-nfc#209]
Is anyone using WebNFC API successfully?

I am attempting to follow the example here: https://whatwebcando.today/nfc.html

Blackview BV6000s Android phone. Chrome browser with both required flags enabled.

The code fails with "nfc" not being found in the navigator object. 

Thanks in advance for any advice.

**Comment by M600LT** [comment]
Sorry, after more research I found the section on needing to serve the pages over https, hopefully this will resolve the issue.

**Comment by anssiko** [comment]
That is correct, the Web NFC API is only exposed to pages served over https.

(Protip: when you see the [SecureContext](https://heycam.github.io/webidl/#SecureContext) keyword atop the interfaces in the specs, you know this restriction applies.)
