### ISSUE TITLE
Add method to reading event to get serial if available

### ISSUE THREAD

**Issue by kenchris** [w3c-cg/web-nfc#212]
We can easily get this via Android and other platforms. Here is the Android info:

![image](https://user-images.githubusercontent.com/1101339/53816806-8c9eaf00-3f64-11e9-9bb9-08500a7adb2c.png)

**Comment by Stryker93** [comment]
Great, thank you for adding!

**Comment by kenchris** [comment]
@domenic how do you think we should expose these? They seem to be either 4 or 7 bytes long, so we should return a sequence? or as a string with either `-` or `:` separating the numbers?

**Comment by kenchris** [comment]
In USB it is a UCHAR and it is exposed in Web USB as a `DOMString`: https://wicg.github.io/webusb/#dictdef-usbdevicefilter

@reillyeon

**Comment by kenchris** [comment]
I think a string is easiest to deal with from JavaScript, so went for a ASCII hex digit string separated by `:`
