### ISSUE TITLE
Use NotAllowedError

### ISSUE THREAD

**Issue by kenchris** [w3c-cg/web-nfc#214]
The WebIDL spec describes `SecurityError` as "the operation is insecure," and `NotAllowedError` as "the request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission."

This seems to clearly indicate that permission errors should generate a `NotAllowedError`.

**Comment by Honry** [comment]
@kenchris, looks like this is the fixed PR: https://github.com/w3c/web-nfc/pull/236
