### ISSUE TITLE
Out of date statement about "NFC" object in section 9.3

### ISSUE THREAD

**Issue by DonnaWuDongxia** [w3c-cg/web-nfc#215]
As the "NFC" has been deleted, following words seem like be out of date in section 9.3:

"Each Window object where NFC is exposed has a separate NFC instance. The visibility and focus state of the Window object determines the suspended state of the associated NFC instance. "

**Comment by anssiko** [comment]
Thanks for reporting @DonnaWuDongxia!

I believe this is a leftover from spec update that split `navigator.nfc` into global `NFCWriter` and `NFCReader` constructors.

Cc @kenchris

**Comment by kenchris** [comment]
Yes, feel free to send PRs for this

**Comment by kenchris** [comment]
@Honry didn't you fix this?

**Comment by Honry** [comment]
Ah, I didn't realize there's already an issue for old "NFC" instance, sorry for the duplication.
Fixed in https://github.com/w3c/web-nfc/pull/273, let's close it now.
