### ISSUE TITLE
NFCReader should contain those members of NFCReaderOptions?

### ISSUE THREAD

**Issue by leonhsl** [w3c-cg/web-nfc#219]
http://w3c.github.io/web-nfc/#constructing-an-nfcreader-object

> For each key → value of options:
If key equals "url", set reader.[[Url]] to value.
Otherwise, if key equals "recordType", set reader.[[RecordType]] to value.
Otherwise, if key equals "mediaType", set reader.[[MediaType]] to value.
Otherwise, if key equals "compatibility", set reader.[[Compatibility]] to value.

However, NFCReader definition does not have such members: Url, RecordType, MediaType, and Compatibility.

**Comment by kenchris** [comment]
These should be internal slots on NFCReader yes - we need a section listing the internal slots for the `NFCReader` object

**Comment by leonhsl** [comment]
Now the new place for this problem is at http://w3c.github.io/web-nfc/#the-scan-method.

**Comment by Honry** [comment]
@leonhsl, @kenchris, I am working on it. :)
