### ISSUE TITLE
NFC Access with localhost but not in a local network

### ISSUE THREAD

**Issue by jonas3210** [w3c-cg/web-nfc#223]
Hi,
i tested the webnfc with a localhost server, remote debugging and everything works fine. But when i use a server in a local network with a static ip address the navigator.nfc object is suddenly undefined. Any ideas?

**Comment by cyberphone** [comment]
I believe HTTPS is required when not using "localhost"

**Comment by anssiko** [comment]
@cyberphone is correct, HTTPS is required. For development purposes localhost is whitelisted.
