### ISSUE TITLE
Should we just ignore the Abort signal and wait for push response for cannot cancel case?

### ISSUE THREAD

**Issue by DonnaWuDongxia** [w3c-cg/web-nfc#239]
In the SPEC, step 8.2 in the [push method](https://w3c.github.io/web-nfc/#the-push-method):

"If the instance has already initiated NFC data transfer, reject p with "NoModificationAllowedError" DOMException and abort these steps."

If we fail to cancel the push request,  push request may succeed or fail with a different error. If we just reject the promise with  a "NoModificationAllowedError" exception, the developer may lose detailed imformation.  So shall we just rely on the push response if the the operation cannot be canceled?

Actually, for current case(the NfcImpl.java on Android), if we fail to cancel the push request, the push response will always be called before cancel response. So "NoModificationAllowedError" exception should never occur.

**Comment by DonnaWuDongxia** [comment]
Discussions during code review is here: https://chromium-review.googlesource.com/c/chromium/src/+/1680418/1/third_party/blink/renderer/modules/nfc/nfc_writer.cc#168

**Comment by zolkis** [comment]
If the implementation knows exactly what happened, the API should allow that information reach the developer. (BTW I am on holiday this week and mostly out of internet reach).
