### ISSUE TITLE
android.nfc.NfcAdapter.enableReaderMode() has no failure cases

### ISSUE THREAD

**Issue by leonhsl** [w3c-cg/web-nfc#242]
https://w3c.github.io/web-nfc/#dom-nfcreader-start step 3.2 says 
> make a request to all NFC adapters to listen to NDEF messages

and step 3.3 says 
> If the request fails, then
Let e be the result of creating a "NotSupportedError" DOMException.

android.nfc.NfcAdapter.enableReaderMode() [1] does what step 3.2 says, but this function always succeeds in registering a ReaderCallback for receiving notifications from the platform, it has no failure cases, so what does step 3.3 mean for 'If the request fails'?

[1] https://developer.android.com/reference/android/nfc/NfcAdapter.html#enableReaderMode(android.app.Activity,%20android.nfc.NfcAdapter.ReaderCallback,%20int,%20android.os.Bundle)

**Comment by kenchris** [comment]
That might not be the case for other platforms

Also, what happens if the Android device doesn't even support NFC? Or NFC is disabled?

**Comment by leonhsl** [comment]
We (Chromium impl) will fire the error event NotReadableError in case that NFC is not supported or is disabled, as described by step 2 of https://w3c.github.io/web-nfc/#dom-nfcreader-start.
The used APIs are android.content.Context.GetSystemService(Context.NFC_SERVICE) and android.nfc.NfcAdapter.isEnabled().

**Comment by kenchris** [comment]
OK, let's fix the spec then
