### ISSUE TITLE
Well-known stores data in the TYPE field and not in the PAYLOAD one

### ISSUE THREAD

**Issue by kenchris** [w3c-cg/web-nfc#244]
https://www.oreilly.com/library/view/beginning-nfc/9781449324094/ch04.html

![image](https://user-images.githubusercontent.com/1101339/62115022-063e8d00-b2b8-11e9-8cce-2528f3cb8ebd.png)

@Honry

**Comment by Honry** [comment]
@kenchris, so, another issue from your picture, it should be 'Absolute-URI records (TNF 3)' rather than 'Absolute-URL records (TNF 3)', right?

**Comment by kenchris** [comment]
These names don't matter and we use URL on the web, not URI
