### ISSUE TITLE
Smart Poster Well-Known doesn't seem to actually store a URL itself

### ISSUE THREAD

**Issue by kenchris** [w3c-cg/web-nfc#245]
Instead it just indicates that the tag is to be considered a SmartPoster and additional records will fill in the data, thus it must contain a URL one, but can also contain an additional text record to give description and even records to show images etc.

We need to understand this better and improve the handling, testing and spec

![image](https://user-images.githubusercontent.com/1101339/62115240-633a4300-b2b8-11e9-981d-4d910728d0df.png)

https://www.oreilly.com/library/view/beginning-nfc/9781449324094/ch04.html#table-appresults

**Comment by kenchris** [comment]
![image](https://user-images.githubusercontent.com/1101339/62115546-e65b9900-b2b8-11e9-8a6a-567c9de4593a.png)

**Comment by kenchris** [comment]
Blogpost showing how to read from Android: http://mynewandroidtutorial.blogspot.com/2015/03/nfc-android-read-ndef-tag-textlink.html

NDEF data can span multiple records as indicated in the header. We probably need to check very well how this is handled by the spec

**Comment by kenchris** [comment]
https://github.com/w3c/web-nfc/issues/249 has an example showing that this is using composed records within the payload field

**Comment by kenchris** [comment]
My suggestion is that we change the type for Smart Posters to `"smart-poster"` instead of `"url"` today. That is a first step.

After that we can potentially create a `toRecords()` getter

**Comment by Honry** [comment]
A smart poster record looks like this:
![Screenshot_20190809-011303](https://user-images.githubusercontent.com/3271201/62758620-87b0cf00-bab1-11e9-9fc2-ffc19f7ec124.png)

**Comment by Honry** [comment]
> NDEF data can span multiple records as indicated in the header. 

@kenchris, so the CF field should be 1 for a smart poster record?

**Comment by kenchris** [comment]
No, these are embedded records! Records inside the payload field of the So record

**Comment by kenchris** [comment]
No, these are embedded records! Records inside the payload field of the So record

**Comment by Honry** [comment]
Aha, got it.

**Comment by kenchris** [comment]
It can actually contain a lot of records, like multiple text ones (for different languages), image data (not sure how they store that) and even signature records (another NFC spec) adding additional security (like you don't want people to set up alternative stickers at a movie teater pointing to a phishing site)

**Comment by kenchris** [comment]
91 01 1B 55 ...

> 0x91.toString(2)
'10010001' message begin, no chunked flag, small record, well-known
> 0x01 
type length 1
>0x1B
payload length 11 (flag + google.com)
> 0x55
"U"
>0x02
https://www. 
>0x67 (g) 6F (o) 6F (o) 67 (g) 6C (l) 65 (e) 2e (.) 63(c) 6f(o) 6d (m) - google.com

**Comment by kenchris** [comment]
[0x51.toString(2), 0x01.toString(2), 0x0b.toString(2), String.fromCharCode(0x54), 0x02.toString(2), String.fromCharCode(0x7a), String.fromCharCode(0x68)]

(7) ["1010001", "1", "1011", "T", "10", "z", "h"]

begin, chunked record, well-known
type length 1
payload length 11
type T (0x54 / 1010100)
UTF8 encoding, language length 2 (00000010)
'zh'
'my title'

I don't get though why it is chunked... there are no more chunks... and why not "message end"?

Maybe that app just wrote it wrong and is still able to read it

**Comment by kenchris** [comment]
Example of a complex Smart Poster record with sub records.

![sp1](https://user-images.githubusercontent.com/1101339/64166054-95eed280-ce46-11e9-9035-4d2dd042d497.PNG)

![sp2](https://user-images.githubusercontent.com/1101339/64166075-a737df00-ce46-11e9-92ac-7b3c69841baf.png)
