### ISSUE TITLE
Writing algorithms nicely split up into sections, do the same for reading

### ISSUE THREAD

**Issue by kenchris** [w3c-cg/web-nfc#246]
Writing algoritms has subalgos like "Mapping string to NDEF", we could do the same the other way around, like "Mapping NDEF Well-Known (text) to string"

**Comment by kenchris** [comment]
Maybe call it "parsing NDEF Well-Known (text) record", not sure

**Comment by Honry** [comment]
@kenchris, looks like we've done this. :)
