### ISSUE TITLE
URL objects

### ISSUE THREAD

**Issue by annevk** [w3c-cg/web-nfc#26]
Please don't use URL objects in data structures: https://url.spec.whatwg.org/#url-apis-elsewhere

(I would also suggest not referencing all of these out-of-date forks of WHATWG Standards. That doesn't seem helpful to readers.)

**Comment by zolkis** [comment]
The problem we have in the NFC spec is that we expose incoming data types as 

```
typedef (DOMString or URL or Blob or JSON) NFCData;
```

Now if `URL` becomes `USVString` then in JS it will be normal string, indistinguishable from text type. That means if we get rid of `URL` objects, we need to carry the type of the original information as a property (like `type: "url", value: "www.mydomain.com"` vs `type:"text", value: "www.mydomain.com"`), which is not very web'ish either, then this will roll on and change the whole API. <_scratching head_>

**Comment by annevk** [comment]
That looks like a problematic structure either way. You cannot distinguish JSON from a string.

**Comment by zolkis** [comment]
In the current implementation, JSON is exposed as Object (property bag) to clients, URL as a URL object, Blob as Object. When a client gets an Object, it can use `instanceof` to tell it was Blob; if it was not a blob, then it was JSON. This works now, but I don't know which evil is worse: using URL object, or carrying type along in a property. Any best practice on this nowadays?

**Comment by annevk** [comment]
What's the underlying representation you're trying to model?

**Comment by kenchris** [comment]
NFC allows you to store different kinds of data. For write, we could just have multiple functions, but I am not sure what would be the best model for read. Push API seems to have http://www.w3.org/TR/push-api/#idl-def-PushMessageData which has different getters.

**Comment by annevk** [comment]
Right, what Push does is based on Fetch. Still, what types of data do we have and how are they exposed underneath?

**Comment by kenchris** [comment]
It can store values like URL (slightly "compressed" by NFC like the new eddystone URLs from physical web), string, and binary data (mime type). We also use a special record for storing json.

http://w3c.github.io/web-nfc/#web-nfc-payload

**Comment by annevk** [comment]
It seems push does not have metadata to include the type. For `Request` and `Response` objects in Fetch that is expected to be delivered through the `Content-Type` header and necessary for the correct extraction of certain types. If you want something analogous I would expect:

``` webidl
interface NFCData {
  readonly attribute NFCDataType type;
  ArrayBuffer arrayBuffer();
  ...
  USVString url();
}
enum NFCDataType { "url", "string", "opaque" };
```

**Comment by domenic** [comment]
+1 to @annevk's design. Alternately, a design like `{ type: "url", data: ... }` `{ type: "text", data: ... }` seems fine. Anne's design is better to communicate that NFC's metadata is not relevant and you want the ability to deserialize in multiple ways as appropriate for the use case. The `{ type, data }` seems a bit better to give a more direct mapping to NFC (although in that case just exposing TNF and MIME type would be more appropriate).

**Comment by kenchris** [comment]
What @annevk suggests is pretty aligned when what I was suggesting originally :-) so I am on board with that. @zolkis what is your take?

**Comment by domenic** [comment]
Also I think the proper name for Blob-with-mimetype is File?

**Comment by annevk** [comment]
No, Blob-with-filename is File. Blob always has a MIME type (though it may be unknown).

**Comment by domenic** [comment]
Right, sorry, I was doing so well for early-morning and then I had to go and blow it :P. I'll go get breakfast and coffee now...

**Comment by zolkis** [comment]
@domenic 

> The { type, data } seems a bit better to give a more direct mapping to NFC (although in that case just exposing TNF and MIME type would be more appropriate).

There is some overlap in NFC regarding TNF and MIME types vs mappable JS types, so for _Web_ NFC we have already done a slight mapping [here](http://w3c.github.io/web-nfc/index.html#web-nfc-payload). Then, we didn't mean exposing the low level NFC details in this spec - for that we still have the older WG spec which follows low level details very well. This spec is more like "rethinking NFC usage for the Web", and the argument would favor @annevk 's design (indeed we have iterated through a similar design with @kenchris earlier). I'd rather start with

``` webidl
enum NFCDataType { "url", "string", "json", "blob" };
interface NFCData {
    readonly attribute NFCDataType type;
    Blob blob();
    JSON json();  // same as 'Object json();'
    USVString url();
    DOMString text();
    // ArrayBuffer arrayBuffer(); // skip this if we don't expose the low level content
}
```

since in that case we have some indication how the content should be handled by the client. Functions may throw type exceptions. But I might miss the details behind the `"opaque"` type idea.

Thank you all for helping in this.

**Comment by domenic** [comment]
That design sounds pretty good. Although I would include arrayBuffer() if you are including blob(). Otherwise you are just telling users that you hate them and want to subject them to the pain that is FileReader :P.

**Comment by zolkis** [comment]
Indeed, even the examples used FileReader :). If we skip the idea of exposing low level content, then we can dedicate arrayBuffer() to Blob(). Or, if we ever wanted to expose that, we could choose a special name for that purpose.

**Comment by kenchris** [comment]
So I guess @annevk was suggesting using "opaque", which could then be read with blob() or  arrayBuffer() ?

**Comment by annevk** [comment]
Yeah, that was my idea. I'm not sure I'd expose `Blob` if you can do `ArrayBuffer`. Doesn't make much sense to offer the asynchronous variant if you offer the bytes synchronously already. If it's about the `type` that a `Blob` can expose you really ought to expose that somehow. Does NFC carry a MIME type?

**Comment by kenchris** [comment]
Yes, it does for binary data

**Comment by annevk** [comment]
So was your idea to expose that through `Blob`? It seems exposing it directly on `NFCData` would be simpler?

**Comment by kenchris** [comment]
Yeah that is an option. Just 'DOMString mimeType()' ?

**Comment by annevk** [comment]
What is the MIME type if the underlying data is a URL or a string? Just blank? It seems you could just offer `type` and either it's the blessed "url" or "string", and a full blown MIME type otherwise. Also, is the underlying MIME type restricted to 0x00 to 0x7F? In that case you want `ByteString`.

**Comment by kenchris** [comment]
Are there other existing examples of APIs like this in the web platform?

**Comment by annevk** [comment]
`DataTransfer` has something similar with magic "text" (better than string actually) and "url" values that map to text/plain and text/uri-list.

**Comment by annevk** [comment]
You could either do that or keep them distinct, with a `type` property getter and a `mimeType` property getter. If the former returns "opaque", the latter will not be the empty string. Kind of depends on how you expect developers will want to branch their code. Seemed reasonable to me that you'd just have:

`````` js
if(data.type === "url") {
  ...
} else if(data.type === "text") {
  ...
} else if(data.type === "image/png") {
  ...
} else {
  reportError()
}```
``````

**Comment by zolkis** [comment]
Since JSON, text and URL could be mapped to MIME types (`application/json`, `text/plain`, and `text/url`) indeed we could go with

``` webidl
interface NFCData {
    readonly attribute DOMString mimeType;
    ArrayBuffer arrayBuffer();
    JSON json();  // same as 'Object json();'
    USVString url();
    DOMString text();
}
```

**Comment by kenchris** [comment]
JSON and text can be mapped to different mime types, I like what @annevk suggested more

**Comment by annevk** [comment]
Actually, `JSON` needs to be `any` and it seems I did that wrong in Fetch. `true` or `1` is valid JSON.

**Comment by zolkis** [comment]
> JSON and text can be mapped to different mime types

But it's a bit awkward to have 2 type specifiers, like "type" and "mimeType", and I think we could manage with one - this still permits having different MIME types for text and JSON.

**Comment by kenchris** [comment]
That was @annevk suggestion.

ByteString type; // "text", "json", "url", or mime type

**Comment by annevk** [comment]
Does the NFC protocol have JSON as a native type? Or is that just opaque that happens to utf-8 decode and parse as JSON?

**Comment by zolkis** [comment]
Yes, but "text" and "json" have MIME types, and user agents could expose then as such.

**Comment by kenchris** [comment]
@annevk the latter. We use a special record for json

**Comment by domenic** [comment]
I am a bit confused. The method-based design makes sense only if the same data can be deserialized multiple ways. E.g. I could take the same NFCData and get it as an arrayBuffer, as json, as text, and maybe even as a URL. Is that the case? Or is the design instead that all but one of those methods would throw?

**Comment by kenchris** [comment]
@domenic that is the reason why I was a bit ambivalent about this API when I suggested it long ago, but it is consistent with Push API

**Comment by annevk** [comment]
@kenchris so why not map directly what NFC does? "text", "url", and everything else is a MIME type plus bytes. Then you have convenience methods that extract the data, some of which will may fail if the data is incorrect.

**Comment by domenic** [comment]
Wait, but what is the answer?

**Comment by zolkis** [comment]
JSON is in fact Media type as defined in [RFC2046](TNF=2) with associated MIME type "application/json".

**Comment by zolkis** [comment]
The spec should state the conditions of throwing in readers. With the strictest policy, yes, only one would not throw.

**Comment by annevk** [comment]
@zolkis there's also e.g., `application/vnd.github+json` and various others JSON MIME types.

**Comment by domenic** [comment]
If the design being discussed is that all but one of those methods could throw, then this is a terrible design. Symmetry with Push is not a good reason.

In that case I would suggest instead

```
interface NFCData {
    readonly attribute DOMString mimeType; // or type? or both?
    readonly attribute any data; // ArrayBuffer or USVString or DOMString or JSON
}
```

**Comment by zolkis** [comment]
I love this.

**Comment by zolkis** [comment]
> there's also e.g., application/vnd.github+json and various others JSON MIME types.

That would be conveyed as Blob with the given MIME type, exposed as

``` javascript
{
   type: "application/vnd.github+json",
   data: 0
}
```

and on NFC level it would be a TNF 2 media message with the given MIME type.

What I meant with the `application/json` was for writing (default MIME type for JSON).

**Comment by kenchris** [comment]
@domenic How would you deal with the writer functions? Have separate ones for the types? or automatically try to detect what any represents?

**Comment by zolkis** [comment]
I think we could do a default mapping based on `instanceof`.

**Comment by kenchris** [comment]
@zolkis i'm just wondering whether it will be too much magic and result in inconsistencies across implementations

**Comment by domenic** [comment]
I can't find "writer functions" in the spec but I would expect a symmetric interface: `write({ mimeType: "...", data: "..." })`. No type inference or magic needed. You would define a dictionary counterpart to NFCData for this purpose.

**Comment by zolkis** [comment]
Right now we have

``` webidl
[NoInterfaceObject]
interface NFCMessage {
    readonly    attribute USVString     scope;
    readonly    attribute sequence<any> data;
    // (DOMString or URL or Blob or JSON)
};
```

and this needs some update now, but the types are perfectly determinable for writing.
If we want to be strict, we can do what @domenic suggests.

**Comment by zolkis** [comment]
That is, 

``` webidl
dictionary NFCMessage {
    USVString     scope;
    sequence<NFCRecord> data;
};

dictionary NFCRecord {
    DOMString    mimeType;
    any data;
};
```

**Comment by kenchris** [comment]
How does all this sound to you @annevk  ?

**Comment by annevk** [comment]
I would do s/`mimeType`/`type`/. Otherwise this seems fine. `scope` looks suspect too, but I suppose we cannot get rid of that due to service workers?

**Comment by kenchris** [comment]
OK, what is the best type for storing the mime type? ByteString as suggested earlier?

**Comment by annevk** [comment]
@kenchris again, what does the underlying protocol store it as? If it's bytes, and not utf-8 bytes, `ByteString` would make the most sense. (We should be as low-level as possible, while within security constraints, and still providing a somewhat attractive API.)

**Comment by kenchris** [comment]
Sorry for all the questions :-) I just want to get this right.

'scope' is not for SW, but a way to know which site actually wrote to the TAG, and it allows for the site to use the path to differentiate/id the data they stored. Would be good if you could read the sections about this in the spec

**Comment by zolkis** [comment]
> I would do s/mimeType/type/. 

Perfectly fine!

>  scope looks suspect too, but I suppose we cannot get rid of that due to service workers?

Scope needs a serious discussion. See also #22 , and we just closed #15. Hence, Occam would remove it for the moment...

**Comment by kenchris** [comment]
@annevk I guess that doesn't just depend on how it is stored on the NFC tags but also how the native NFC APIs expose it. We would have to look at that.

**Comment by zolkis** [comment]
As for (MIME) `type`, IMHO developer convenience should be the priority. It's not a low level information we should try to maintain at low level, but a helper to access the low level information.

**Comment by kenchris** [comment]
@annevk on Android, the API exposes it as String (UTF-16):

```
String  toMimeType()
Map this record to a MIME type, or return null if it cannot be mapped.
```

**Comment by annevk** [comment]
@kenchris well, `ByteString` also returns a string (for convenience). It's just that the underlying representation is bytes. I guess you're saying that on Android the underlying representation is a string, though is this the C or Java API?

@zolkis it's really more a question about the value range than convenience with ByteString vs DOMString vs USVString.

**Comment by kenchris** [comment]
@annevk the Java API: http://developer.android.com/reference/android/nfc/NdefRecord.html - I haven't looked at whether the NDK exposes NFC or not, and how. @zolkis What does neard expose?

**Comment by zolkis** [comment]
> 'scope' is not for SW, but a way to know which site actually wrote to the TAG, and it allows for the site to use the path to differentiate/id the data they stored. Would be good if you could read the sections about this in the spec

Most of it is here (step 6):
http://w3c.github.io/web-nfc/index.html#the-send-method
and the definition is in 
http://w3c.github.io/web-nfc/index.html#terminology

**Comment by zolkis** [comment]
> What does neard expose?

DBUS string (UTF-8), and for the data, byte array (DBUS serialization).
Check http://git.kernel.org/cgit/network/nfc/neard.git/tree/doc/tag-api.txt

**Comment by annevk** [comment]
Sounds like `type` should be USVString then. Somewhat strange that NFC doesn't take its cues from HTTP.

**Comment by kenchris** [comment]
@annevk you still prefer `USVString type` to be "text", "url", "json" or mime type? If you and @domenic agree on that, we can go ahead and spec that.

**Comment by annevk** [comment]
That seems fine to me.

**Comment by zolkis** [comment]
When reading, both "text" and "json" may map to multiple MIME types, therefore it is better to expose those MIME types directly instead of collecting them under one hat and losing that information.

When writing, there could be default MIME types used for text, URL and JSON - we need to map to the NDEF records anyway, so we can't skip on mapping during writes. There the question is how many low level options we expose (TNF, etc) vs automatic type mapping.

**Comment by domenic** [comment]
I don't feel like I understand the issue completely enough to give a strong opinion, but using MIME type seems better than having "text" and "url" and "json"...

**Comment by kenchris** [comment]
There is one thing to have in mind. Things are stored in different records. The mime record is the only one who can store arbitrary data, but the size might be limited on some tags. Also the record for URL stores the URL with some compression, like use a binary code for representing "https://www" similar as Eddystone (https://github.com/google/eddystone/tree/master/eddystone-url).

With @annevk idea, only things stored as mime data would be represented using mimetypes and other record types would have special values like "text", "url" etc

**Comment by zolkis** [comment]
That is well understood (we also have explored that option in the past), but we break up the original NFC records anyway (think about smart poster), and present information to web pages which is basically mapped anyway. Therefore it is more straightforward (for clients) to use a single mapping, and it's interesting only for the read use case - writing does not change. Even the read API does not change, only the values of `type`. So let me edit the spec to record the new API, and I will leave a note about this. Let's wait for implementation feedback and then choose one way.

**Comment by kenchris** [comment]
I am just afraid that regular developers don't really know the mime type of, say URL. Should we use text/uri-list ? or text/x-uri ? or ...

**Comment by zolkis** [comment]
In the particular case of URL, we could specify to use "text/uri-list", then they will know for sure.
However, nothing stops us from using arbitrary strings in the `type` property (in addition to MIME types) which are specific helpers to Web NFC ("url", "text", etc). I was afraid they would create confusion (if developers expect a valid mime type), but from Anne's and your stance I see that is not a problem.
So should we allow using "url" together with URL MIME types and "text" together with text MIME types? We anyway need to specify what exactly do they map to (NDEF record, and MIME type if it's the case).

**Comment by zolkis** [comment]
If we want to proceed with including simplified helper types, and don't want to lose type information, we need to use a variant of Anne's earlier proposal, something like this:

``` webidl
enum NFCDataType { "url", "text", "json", "opaque" };

dictionary NFCRecord {
    NFCDataType type;
    USVString mime;  // the more exact MIME type
    any data; // null || string (text, url, json) || Object (json) || ArrayBuffer (opaque)
};

dictionary NFCMessage {
    USVString scope;
    sequence<NFCRecord> data;
};
```

Unfortunately I don't see how we could merge `type` with `mime` like [here](https://github.com/w3c/web-nfc/issues/26#issuecomment-129872882) without losing information.

If `type == 'text`, or `type == 'url'`, then `data` will contain a string (implementation takes care of the MIME type/encoding), plus `mime` MAY contain additional information or MAY be empty.

Then, if  `type == 'json'`, then `data` may be `null`, `Number`, string, or `Object`, and `mime` contains the originating MIME type (e.g. `application/json`).

Then, if `type == 'opaque'`, then `data` is an ArrayBuffer, and in addition `mime` tells clients how exactly to use it.

We convey type information end to end, mapping to and from appropriate NDEF record types.

Does this sound ok? Name change suggestions? Corrections?

**Comment by annevk** [comment]
This is why I asked what the model is. It sounds like `mime` should not default but should just reflect the underlying value.

**Comment by zolkis** [comment]
We agree. Can I go ahead with this, @kenchris and @domenic ?

**Comment by kenchris** [comment]
Yes, fine with me. Do we prefer mime instead of mimeType? Any existing examples in the web platform? What would you recommend @annevk ?

**Comment by annevk** [comment]
Perhaps `kind` and `type`?

**Comment by zolkis** [comment]
Works for me! I did not dare calling it 'kind' :) - let's see what @domenic says.

Basically one is a basic type (in terms of NFC, i.e. text, url, or object/media/blob), the other is an extended type information. There is some overlap of semantics there, but I think we should be closer to web developers semantics than to NFC.

**Comment by zolkis** [comment]
I have been talking with implementors who say it is too complex with two properties for type and that is right. All underlying platforms expose just (MIME) type and data. 
So let's see if we can merge the two, case by case (just thinking out loud).

A. Mapping for writes
1. Writing text: `data` = "any text", allowed `type` is "text", or "text/plain", or any valid MIME type "text/_anything_". Otherwise reject. Implementations map it to an NDEF record with TNF = 1 Type Text.
2. Writing URL: `data` = "http://valid.url", allowed `type` is "url", or "text/uri-list". Otherwise reject. Implementations map it to TNF=1 Type URI.
3. Writing JSON: `data` = null || _number_ || _string_ || _Object_, allowed `type` is "json" or "application/json". Otherwise reject. Implementations map it to TNF=2 with MIME type "application/json".
4. Writing `data` with JS type _ArrayBuffer_, or _string_, or _Object_ with `type` = _valid_MIME_type_ will result in mapping to TNF=2 with the given MIME type (and it will read back as _ArrayBuffer_, see B.4.).

B. Mapping for reads
1. TNF=1 Type Text is presented as `type` = "text", `data` = "string".
2. TNF=1 Type URI, TNF=1 Type Smart Poster, and TNF=3 Absolute URI is presented as `type`="url", `data` = "string".
3. TNF=2 when MIME type is "application/json" is presented as `type` = "json", `data` = either _null_, or a _number_, or a _string_, or an _Object_.
4. TNF=2 with other MIME types are presented as `type` = _MIME_type_, `data` = _ArrayBuffer_.
5. TNF=4 with type other than `urn:nfc:ext:w3.org:webnfc`, and any other NDEF record type is presented as `type` = "opaque", `data` = _ArrayBuffer_. 

So it seems that my earlier (theoretical) concerns about losing type information are not valid and in practice we could merge the type properties (<_chastising self_>):

``` webidl
dictionary NFCRecord {
    USVString type;  // "url", "text", json", "opaque", or a MIME type
    any data;
};

dictionary NFCMessage {
    USVString scope;
    sequence<NFCRecord> data;
};
```

Would this work?

**Comment by kenchris** [comment]
I guess you want application/*+json as well

**Comment by kenchris** [comment]
What do you mean with valid mime type; are we actually going to check the type against a list or just making sure it consists of a '_/_' pattern?

**Comment by annevk** [comment]
I think you need to write out the mapping algorithms and JavaScript since I see some conflicts around JSON and text and such.

Also, why is it okay to lose precision for TNF 1, 3, and 4?

**Comment by zolkis** [comment]
I think precision is needed when the client has to do the conversion. For the use cases of Web NFC the rest seem to be fine - it is one of the purposes of the API to map NFC to types known in the browsers. But I have no problems exposing the exact underlying information, when available. Could you give one example for conflict for JSON and text, respectively?

**Comment by zolkis** [comment]
@kenchris 

> I guess you want application/*+json as well

Yes, indeed. 

> What do you mean with valid mime type; are we actually going to check the type against a list or just making sure it consists of a '/' pattern?

Implementations will have to do sanity checks on MIME type data: bounds, structure, etc for security reasons. I didn't mean validating against a full list of MIME types - those then would need to be listed in the spec or referenced externally. What is a good compromise there?

**Comment by annevk** [comment]
Well, text is a string and JSON can be too. As for your other point, it's not clear to me why we don't have "smart-poster-url" and "url" for instance. Or why we would hide everything TNF=4.

**Comment by domenic** [comment]
> I am just afraid that regular developers don't really know the mime type of, say URL. Should we use text/uri-list ? or text/x-uri ? or ...

I am not sure your mental model here. For reading, it will be perfectly obvious to developers that `{ type: "text/uri-list", data: "https://example.com" }` is a URL. (Although the crappy "URI" name is unfortunate.) For writing, I doubt developers are going to guess at the type they should use---they'll almost certainly look at docs or the spec anyway. So I don't think this is an issue.

> If we want to proceed with including simplified helper types, and don't want to lose type information, we need to use a variant of Anne's earlier proposal, something like this:

This proposal sounds good to me. Although, reading further, I guess not to implementers?

> Do we prefer mime instead of mimeType? Any existing examples in the web platform? 

I have been investigating this for a different spec, and so far everything I've seen in public APIs has been `type`.

---

> ```
>     USVString type;  // "url", "text", json", "opaque", or a MIME type
> ```

If we can't have kind + type, then I really don't see any value in this over just using a MIME type directly and only. The mapping would be:
- Writing:
  - text: authors supply `"text/*"` and data `"any text"`. Convert data to a string using usual Web IDL/ECMAScript ToString conversion.
  - URLs: authors supply `"text/uri-list"` (ugh) and data `"http://valid.url"`. Convert data to a string, then validate that it's a valid absolute URL; throw if it's not.
  - JSON: authors supply `"application/json"` or `"application/*+json"`. `JSON.stringify` the supplied value (throw if that fails).
  - anything else: authors supply any other non-special mime type plus a BufferSource (= ArrayBuffer or typed array). Any other type throws.
- Reading
  - TNF=1 Type Text => `"text/plain"`, deserialize to DOMString
  - TNF=1 Type URI, TNF=1 Type Smart Poster, and TNF=3 Absolute URI => `"text/uri-list"`, deserialize to USVString
  - TNF=2 mime type `"application/json"` or `"application/*+json"`, `JSON.parse` it (throw if can't be parsed)
  - everything else => mime type as-is, deserialize to ArrayBuffer.

---

All this said I am not an expert and appreciate you guys are doing some hard work to try to map something that is not web-friendly to something that is. My gut instinct would be to expose things on the lowest level possible and then leave the nice web-friendly stuff for later specs or for author libraries, but I understand the effort to do something nicer and will trust you all to do so. I think everyone is on the same page about not using actual URL objects, which was our main concern, and at this point we're all just kind of throwing in ideas as to what seems like a nice API.

**Comment by zolkis** [comment]
We don't hide TNF=4, but expose it as ArrayBuffer without MIME type. Did you mean why do we hide the NDEF fields from developers (e.g. the TNF value), IOW why don't we present a low level interface? That is done by the earlier WG spec pretty well. Should we expose these NFC-specific terms/details for any web page? 

One assumption in Web NFC was that we don't have to be compliant with legacy NFC tags - when we started the CG people wanted to have a web-specific NFC, even so much as total separation between NFC content available for web pages and low level interfaces available through native platforms. This was a security issue from the start. Not having to expose all low level details allowed us to simplify the interfaces, and focus on the us cases by not having to care too much about exact formats.

> Well, text is a string and JSON can be too. 

It is possible to write a string as "application/json" or "text/plain", and read a string as "application/json" or "text/html". I'm not sure I understand the problem. Here I don't see we lose type information that has been written using Web NFC (or even by "legacy" writers).

**Comment by zolkis** [comment]
Thanks @domenic , all this sounds good, I would be fine with all of it.

**Comment by zolkis** [comment]
With the exception that there are cases when we don't have MIME type information (for instance External Type records). For that we need default MIME type (e.g. "application/octet-stream") or just a placeholder like "opaque".

**Comment by domenic** [comment]
"application/octet-stream" seems reasonable.

**Comment by annevk** [comment]
> This was a security issue from the start.

I guess @domenic and I are not familiar with those which makes it a bit harder to design something here.

I do think "url" is better than "text/uri-list" since we these NFC fields don't actually accept or return a list of URLs and there's no clear MIME type for a single URL.

Soonish we'll also have `<script type=module>` which is also not a MIME type but much nicer than something like `<script type=text/module+javascript>` so I don't think that purity matters much. It's not like these types are parsed anyway, they're just treated as a single entity.

**Comment by kenchris** [comment]
You work on the URL spec @annevk, don't you think we could suggest a real URL mime type? Do you know the process for that?

**Comment by domenic** [comment]
I guess I was motivated by hiding everything behind the facade of a mime type so that authors have both a uniform mental model and can use it as a MIME type if necessary (e.g. fetch with content-type header set appropriately). @annevk doesn't think that's as important. I'm not sure either of us feels strongly so maybe you guys could make the decision?

**Comment by kenchris** [comment]
It seems that Robin at least have experience with creating new mime types:

x-www-form-urlencoded   application/x-www-form-urlencoded   [W3C][Robin_Berjon]
http://www.iana.org/assignments/media-types/media-types.xhtml

**Comment by kenchris** [comment]
@darobin ^

**Comment by domenic** [comment]
A slight variant would be to use the word "kind" as in "a web NFC record's kind can be one of: url, text, json, or a MIME type." That seems slightly better than using "type" but allowing things that are not MIME types.

**Comment by annevk** [comment]
If you really wanted it badly feel free to squat "text/url" and I'll add it to the URL Standard and deal with the IETF noise.

**Comment by annevk** [comment]
(@domenic, but then what about `<script type=module>`?)

**Comment by domenic** [comment]
@annevk I guess the analogy you're making is that there's already one place in HTML, or at least there will be, where the word "type" is used but we plan to allow other values than MIME types? _shrug_. It's a hack, and doesn't seem terribly relevant.

**Comment by zolkis** [comment]
What matters for back-compatibility is a consistency of mapping to and from NDEF records. Having additional values for "type", which may be deprecated later, are indeed not terribly relevant. Of course a clean design is preferable :), but with the current constraints I don't have problems addressing URL's as `type == 'url'` or 'text/url' or 'text/uri-list' with the note that in this spec it actually denotes a single URL.

**Comment by annevk** [comment]
Using `kind` and making it a couple special values or a MIME type seems the least problematic to all involved. I would still be interested in hearing about the security issues that preclude sharing some of the underlying data. #2 is quite vague on the manner and it seems @sicking and @jyasskin are not really in agreement as to what is dangerous and what is not...

**Comment by sicking** [comment]
The best way to expose urls is through normal strings. URL objects are IMHO a great library for parsing a URL in order to extract data from it (like the domain name, or query parameters). If someone wants to do that with the data read from a nfc tag, then can easily do that using application logic.

I'm not sure what relevance the security model has here?

**Comment by annevk** [comment]
We kind of strayed from the original subject.

**Comment by zolkis** [comment]
@sicking 

> The best way to expose urls is through normal strings. 

We agree,  for URL's, `data` is always a _url-string_. The discussion is whether 
-  `type` = "text/uri-list" (MIME type), or "url" (our invented value for this)
- or we add a new property `kind` = "url" (invented value) and `type` is irrelevant for URL (for types other than URL it contains the MIME type).

Introducing `kind` (as a base type) + having `type` for MIME type was criticised by implementors as bringing complexity in validating the possible combinations, and the alternative of diluting `type` with extra non-MIME values like "url" is kind of ugly. The third, using purely MIME types would be fine but we don't have a MIME type for URL's yet (we could use "text/uri-list" with web nfc-specific constraint that it denotes a single URL).

> I'm not sure what relevance the security model has here?

Anne asked why do we hide low level NFC information coming from NDEF records, i.e. why not exposing the lowest level of data to web pages (and leave beautification to libraries). I answered that was an outcome of the security related discussion which was outlined in #2. So in this API we try to focus on web-specific use cases of NFC (using types known in the browser), rely on the browser security mechanisms, and additionally use a data storage format which is specific to Web NFC (by adding a special record to the NDEF messages and storing the writing scope in the message). Nevertheless, we can still choose to expose selected low-level information, but then it will be hard to draw the line between low level and high level API's, with the former being needed to comply with NDEF standards.

**Comment by sicking** [comment]
> We agree, for URL's, data is always a url-string. The discussion is whether
> - type = "text/uri-list" (MIME type), or "url" (our invented value for this)
> - or we add a new property kind = "url" (invented value) and type is irrelevant for URL (for types other than URL it contains the MIME type).

I don't care strongly. Though mimetypes are generally a pretty crappy way of exposing types. For exactly this reason. Lots of stuff doesn't have a mimetype. And lots of things have several different mimetypes.

From a security point of view I think we can expose the low-level information once we know that a tag has opted in to being "secure to expose to the web". At least for reading.

**Comment by zolkis** [comment]
@sicking 

> Though mimetypes are generally a pretty crappy way of exposing types. For exactly this reason. Lots of stuff doesn't have a mimetype. And lots of things have several different mimetypes.

Fully agree. And it would be pity to complicate the API because of insufficient coverage of MIME types.

> From a security point of view I think we can expose the low-level information once we know that a tag has opted in to being "secure to expose to the web". At least for reading.

Yes. And tags express that by being a "web-nfc" tag (contain the special record/ writing scope).
We will reiterate then what low-level information is worth exposing.

@annevk 

> If you really wanted it badly feel free to squat "text/url" and I'll add it to the URL Standard and deal with the IETF noise.

That would be one good solution, IMO. So the value of `type` would be a MIME type, plus "text/url" which may become a MIME type later. Good enough for me.

> Using kind and making it a couple special values or a MIME type seems the least problematic to all involved. 

Did you mean using one property like above, but instead of `type` let's call it `kind` and let it have MIME types plus a couple of special values like "url" (or even "text/url" FWIW)?
Or did you mean the additional property `kind` along with `type` which is meant to be a standard MIME type?

**Comment by darobin** [comment]
My recommendation if you go the `text/url` route is to just squat it and implement it. Only at the very end of the process, if you have no other choice, then register it with IANA. The registration process is cryptic and poorly designed, it makes many other standard processes look fun. The registration form is buggy. The expert reviewers are, well... just to give an example the reviewer for my registration of `application/xhtml+xml` in 2014 objected because I was not referring to XHTML 2.0.

Once you've accumulated enough fait accompli that you can't be derailed by that sort of feedback, only then should you bother. And even then, if I had to do it again I would probably suggest starting a MIME type registry at the WHATWG instead.
