### ISSUE TITLE
respec issues

### ISSUE THREAD

**Issue by kenchris** [w3c-cg/web-nfc#261]
@honry @marcoscaceres

how do I link to something like "typed-array-types" in web idl, as well as "unrestricted-double"

`{{unrestricted double}}` doesn't work, but `{{double}}` does

**Comment by Honry** [comment]
> {{unrestricted double}}

I've encountered this too, we can find it in xref UI, https://respec.org/xref/,
maybe it's a ReSpec issue? Not sure, @marcoscaceres, need your help. :)

**Comment by marcoscaceres** [comment]
The "unrestricted double" issue in now fixed in latest release. If you hit other Respec bugs, please make sure to file them here: http://github.com/w3c/respec/ ... there are a few other contributors, so they can also help resolve things without needing to rely on me too much.

**Comment by Honry** [comment]
Thanks @marcoscaceres, fixed in https://github.com/w3c/web-nfc/pull/265

**Comment by Honry** [comment]
@kenchris, we can close it now.
