### ISSUE TITLE
Fix type for external type

### ISSUE THREAD

**Issue by kenchris** [w3c-cg/web-nfc#262]
External type is for custom data, so it is quite important to know what external type was encountered.

Currently we just set the type to `opaque` which is quite useless and forces the developer to do unreliable buffer sniffing.

I suggest we expose the URN type as the type instead like `urn:nfc:ext:intel.com:customrecord`

It is currently an enum so not sure how to do this spec wise

@Honry

**Comment by kenchris** [comment]
@marcoscaceres do you have ideas?

**Comment by marcoscaceres** [comment]
Urns ⚱️ no es bueno. Just use a string and a registry?

**Comment by kenchris** [comment]
But URNs are part of the NFC spec so no way of getting around them :-)

**Comment by marcoscaceres** [comment]
I see. Can you give an example of what you are trying to do. I’ve not looked at nfc in any detail.

**Comment by kenchris** [comment]
Fixed
