### ISSUE TITLE
Security section

### ISSUE THREAD

**Issue by kenchris** [w3c-cg/web-nfc#264]
When I copied the security section content to the wake lock spec, I was told that we cannot write it that way so need to dig up the old discussion and fix it here as well

![image](https://user-images.githubusercontent.com/1101339/62370761-49586480-b533-11e9-944d-572427ffce2c.png)

**Comment by kenchris** [comment]
Relevant link: https://github.com/w3c/wake-lock/pull/164

**Comment by zolkis** [comment]
Fixed by #443. 
Please check and close if it's the case.

**Comment by beaufortfrancois** [comment]
@kenchris Can you check if this issue is addressed by #443 as suggested by @zolkis?

**Comment by kenchris** [comment]
As far as I can tell, this is no longer an issue
