### ISSUE TITLE
Throw "TypeError" instead of "Syntax" when parsing a URL fails

### ISSUE THREAD

**Issue by Honry** [w3c-cg/web-nfc#268]
>2. Let urlRecord be the result of [parsing ](https://url.spec.whatwg.org/#concept-url-parser)record's data.
>3. If urlRecord is failure, throw a "SyntaxError" DOMException and abort these steps.

>4. Let urlRecord be the result of [parsing ](https://url.spec.whatwg.org/#concept-url-parser)id.
>5. If urlRecord is failure, throw a "SyntaxError" DOMException and abort these steps.

These would be better to throw "TypeError". 

@kenchris @marcoscaceres

**Comment by marcoscaceres** [comment]
I'd say yes... looking at what the URL spec does. These are TypeError... the message of the type error could say in detail what's actually wrong, but that's a "quality of implementation" thing.
