### ISSUE TITLE
Notify NFCReaders of failures when trying to get a message from a tag?

### ISSUE THREAD

**Issue by leonhsl** [w3c-cg/web-nfc#279]
See
https://developer.android.com/reference/android/nfc/tech/Ndef.html#getNdefMessage().
Once a tag is discovered, we call `android.nfc.tech.Ndef.getNdefMessage()` to try to get a message from it, which may
  - return null if the tag is in the `INITIALIZED` state, i.e. formatted but empty
  - throw exceptions: `TagLostException,` `IOException,` or `FormatException`

In such cases do we need to let all active `NFCReaders` be aware of these failures so that they can choose how to proceed next? i.e. dispatching some error events properly to `NFCReaders.`

Currently http://w3c.github.io/web-nfc/#the-nfc-reading-algorithm only describes the case that a ndef message has already been gotten from the tag, so does the implementation in Chromium.

**Comment by kenchris** [comment]
So I assume the problem we have here is that 1) is an empty formatted tag that doesn't even have the empty record?

**Comment by leonhsl** [comment]
Exactly.

**Comment by kenchris** [comment]
Could we return an empty record?

**Comment by riju** [comment]
For context, this [came up in review](https://chromium-review.googlesource.com/c/chromium/src/+/1736167/2/services/device/nfc/android/java/src/org/chromium/device/nfc/NfcImpl.java#561). In chromium implementation, I do see a [kNfcEmpytMessage](https://cs.chromium.org/chromium/src/third_party/blink/renderer/modules/nfc/nfc_constants.cc?g=0&l=40) used to throw an exception while pushing empty message to tag. We could use something similar while reading also ?

**Comment by kenchris** [comment]
For TagLostException, we can just avoid dispatching the event as no tag was fully read.

**Comment by kenchris** [comment]
We should probably do like Generic Sensor and have an onerror event handler as well, which somehow can handle the error cases

**Comment by leonhsl** [comment]
So, for the null ndef message case we dispatch a reading event with a ndef message containing just an empty record; for `IOException` and `FormatException` cases we dispatch an error event. Right?

Note: These events are dispatched to ALL active readers, without any message filtering for matching their reader options.

**Comment by kenchris** [comment]
Sounds good, but I think we might want to consider adding a "formatted" type, similarly to the "empty" type

**Comment by beaufortfrancois** [comment]
According to https://github.com/w3c/web-nfc/issues/367, reading non-formatted tags result in a onreading event with empty records array for NDEFMessage.
I think we can close this issue right?

**Comment by beaufortfrancois** [comment]
Ooops! We should not close it. Dispatching event errors in `IOException` and `FormatException` cases is not supported anymore as we got rid of NDEFErrorEvent.

**Comment by kenchris** [comment]
So you suggest we readd the error event for that? Or other solutions?

**Comment by beaufortfrancois** [comment]
I didn't find any other solution sadly that satisfies me but re-adding the NDEFError event.
@zolkis for thoughts as well.

**Comment by zolkis** [comment]
> I didn't find any other solution sadly that satisfies me but re-adding the NDEFError event.

I think so, too.

**Comment by beaufortfrancois** [comment]
For info, I have a PR at https://github.com/w3c/web-nfc/pull/432 that attempts to fix this.
