### ISSUE TITLE
A record might have no payload

### ISSUE THREAD

**Issue by kenchris** [w3c-cg/web-nfc#309]
ie PAYLOAD LENGTH field is 0 and the PAYLOAD field is not present. We need to make sure we actually handle that and that our `to*` methods return `undefined` or similar (at least it makes sense that `toJSON` returns that

**Comment by kenchris** [comment]
Same, what happens if I write a 0 length ArrayBuffer as opaque... what is written? and do we get the same back when reading such a record and calling toArrayBuffer?

**Comment by zolkis** [comment]
IMHO `toJSON()` will never return `undefined` unless we feed `undefined` to it, i.e. when `record.[[PayloadData]]` is `undefined`. 

The result of `JSON.stringify(undefined)` is `undefined`, but `JSON.parse(undefined)` will through (not valid JSON).

In NFC specs the guiding field is the payload length, PAYLOAD might be there or might be missing.

For writes, the current spec should be fine (when feeding `undefined` to writes).
For reads, we should clarify the parse algorithms to be explicit about the use of `undefined`.

**Comment by kenchris** [comment]
Try with Symbol('hi') and BigInt()

**Comment by kenchris** [comment]
Values that do not have a JSON representation (such as undefined and functions) do not produce a String. Instead they produce the undefined value. In arrays these values are represented as the String null. In objects an unrepresentable value causes the property to be excluded from stringification.

**Comment by zolkis** [comment]
Tried to address in #319

**Comment by zolkis** [comment]
@kenchris can we close this? or still valid?

**Comment by kenchris** [comment]
I don't think so, like look here:

![image](https://user-images.githubusercontent.com/1101339/64010834-d08cfe00-cb1a-11e9-8029-d88070b6da12.png)

That field might not even be present

**Comment by kenchris** [comment]
Also here we never set the `[[PayloadData]]`:

![image](https://user-images.githubusercontent.com/1101339/64010962-0631e700-cb1b-11e9-81c7-77d8238da80b.png)

**Comment by kenchris** [comment]
We should probably also factor that out in its own algo like the others

**Comment by zolkis** [comment]
Right, I have updated only the steps that use the PAYLOAD bytes.

The ones (quoted above) that just attribute PAYLOAD, I didn't change since if PAYLOAD is not present (i.e. undefined), I assumed the [[PatloadData]] will also be `undefined`. Or should this be explicitly specified (for undefined, or null?).

Factoring out in a new algo makes sense.

**Comment by kenchris** [comment]
I think it is better if we spell it out, also we cannot say "set to the byte sequence of the PAYLOAD field" if that doesn't exist. As am implemented I would just assume that it alwasy exists

**Comment by kenchris** [comment]
Did you make any of these change @zolkis?

**Comment by zolkis** [comment]
Not (yet)

**Comment by zolkis** [comment]
Seems to be fixed by #323

**Comment by beaufortfrancois** [comment]
If we're good, can we close this issue?
