### ISSUE TITLE
Fire the 'message' event

### ISSUE THREAD

**Issue by jyasskin** [w3c-cg/web-nfc#31]
Nothing in the spec actually fires the event in response to NFC activity. Presumably this is where you'd filter messages to ones with an `id` field matching the current origin.

**Comment by zolkis** [comment]
Yes, this needs to be elaborated in more detail in [8.1.1](http://w3c.github.io/web-nfc/index.html#the-message-event)

**Comment by zolkis** [comment]
This has become obsolete.
