### ISSUE TITLE
Support reading embedded records: Add toRecords()

### ISSUE THREAD

**Issue by kenchris** [w3c-cg/web-nfc#312]
NDEF records can have embedded records, and actually the well-known Sp (Smart Poster) makes use of that.

Some example of how to read that on Android here: http://mynewandroidtutorial.blogspot.com/2015/03/nfc-android-read-ndef-tag-textlink.html

We should basically add a `FrozenArray<NDEFRecord> toRecords();` or similar.

Developers are allowed to store their own record types within a subrecord in the well-known type, with the restriction that the type name cannot start with an uppercase (lowercase or number thus is fine).

We should think a bit about how to expose these. Potentially we could create a "custom" recordType or similar, and then add a `customType` property, or we should just add it to the recordType, like "custom:userDefinedType001". We don't need to support this initially, but it is something to think about.

**Comment by zolkis** [comment]
If this is additive, I'd wait until the need for the use case in web pages is confirmed by developers.

Especially when I feel the Web NFC spec is getting more and more complex. :)

**Comment by kenchris** [comment]
It is definitely needed if you care about storing data more efficiently. I just had people ask about this at BrazilJS conference. Also it is required for smart-poster and it actually doesn't look that hard to implement. People use it today and are not able to read this data.

> Especially when I feel the Web NFC spec is getting more and more complex. :)

But it is also getting more useful

To be honest, I wasn't aware that it was possible (but of course it is) and people educated me that it is actually quite common for people who use NDEF instead of propriatary protocols on NFC tags.

**Comment by zolkis** [comment]
So you already got the developer need. Anyway it should be additive and not break the existing API / structures, so we need to figure that out now.

**Comment by riju** [comment]
This related to the [smart poster discussions](https://github.com/w3c/web-nfc/issues/245) ? I mean embedded records use cases apart from smart posters ?
