### ISSUE TITLE
Set NDEFRecord#mediaType to "application/octet-stream" for a TNF_UNKNOWN record

### ISSUE THREAD

**Issue by leonhsl** [w3c-cg/web-nfc#325]
I suppose we need to add
> Set record's mediaType to "application/octet-stream".

into https://w3c.github.io/web-nfc/#parsing-ndef-unknown-type-records, because https://w3c.github.io/web-nfc/#data-mapping says 

> 

Any other NDEF record type | "opaque" | "application/octet-stream"
-- | -- | --

**Comment by kenchris** [comment]
yes sounds right!

**Comment by leonhsl** [comment]
Closing due to https://github.com/w3c/web-nfc/pull/332
