### ISSUE TITLE
How does NFCScanOptions#recordType filter external type records?

### ISSUE THREAD

**Issue by leonhsl** [w3c-cg/web-nfc#327]
When reading ndef messages, do we want to match `NFCScanOptions#recordType` exactly for external type records?
By reading the current spec, for `NFCScanOptions#recordType` being '**abc.com:xyz**', we only filter those ndef messages containing at least one external type record with type field being exactly '**abc.com:xyz**'. 

That is to say, we can filter all 'text' records by specifying `NFCScanOptions#recordType` as 'text', so do 'url', 'json', and 'opaque', but we can not filter all external type records.

I want to confirm whether this is expected behavior for matching external type records.

**Comment by kenchris** [comment]
We should be able to filter for external type records, like "w3.org" or "w3.org:a"

That said, you need to know how to handle an external record so supporting something like "*:a" makes no sense, and you can always opt of out doing filtering and you will get all records

I would say that if the start is a domain (contains only valid domain letters and at least a dot following a TLD (top level domain) then we can match that to the external domain before : (exact match).

In addition we could also support doing "w3.org:*" - pros/cons?

@beaufortfrancois @reillyeon

**Comment by leonhsl** [comment]
This relates closely to #331 but aims to clarify how could NFCScanOptions#recordType match external type records.

Note: `w3.org:*` filter is not possible because `*` is a valid character for the custom-type.

> DIGIT                = %x30-39
ALPHA                = %x41-5A / %x61-7A   ; A-Z / a-z
other                = "(" / ")" / "+" / "," / "-" / ":" / "=" /
                       "@" / ";" / "$" / "_" / "!" / "*" / "'" / "."

**Comment by kenchris** [comment]
We will need to allow escaping it like the service worker stuff is doing, but maybe we can ignore it for now, implementation wise.

https://github.com/wanderview/service-worker-scope-pattern-matching/blob/master/explainer.md

I need to look at this when I get back from Japan

Maybe you can look at URLPattern and see if there are any problems for us adopting that

**Comment by kenchris** [comment]
We should support escaping * with \ for now. 

> The \ character escapes the following pattern character.

**Comment by kenchris** [comment]
Going to remove filtering
