### ISSUE TITLE
Consider the filtering names for filtering NDEF messages

### ISSUE THREAD

**Issue by kenchris** [w3c-cg/web-nfc#341]
* Currently we are using `url` (`id`) and `mediaType` but they are not exact matches.
* We don't filter records but the whole NDEF message

We could consider `containsId` or `hasIdMatch` or similar.

This issue is for the discussion of the name

@beaufortfrancois @zolkis @reillyeon

**Comment by zolkis** [comment]
I favor `hasIdMatch` (or similar), but not `id` (which I'd associate with full id matching).

**Comment by kenchris** [comment]
I assume you favor `hasMediaTypeMatch` as well then?

**Comment by kenchris** [comment]
Going to remove filtering
