### ISSUE TITLE
Fix spec issue after things from promise guide moved into web idl

### ISSUE THREAD

**Issue by kenchris** [w3c-cg/web-nfc#342]
![image](https://user-images.githubusercontent.com/1101339/64259914-48e42c80-cf2a-11e9-97db-212d76650728.png)

Either we need to use

![image](https://user-images.githubusercontent.com/1101339/64259955-5bf6fc80-cf2a-11e9-8d7f-2bd9b2b09f70.png)

or

![image](https://user-images.githubusercontent.com/1101339/64259992-69ac8200-cf2a-11e9-86e6-df384c5b0234.png)

**Comment by kenchris** [comment]
Ah should be the former...

**Comment by zolkis** [comment]
Anyway we need to specify what happens on fulfillment and rejection. Transforming a promise is before settling, right?

**Comment by kenchris** [comment]
This is the text that was removed from promise guide:

"<dfn id="transforming-by">Transforming</dfn> <var>p</var> with a fulfillment and/or rejection handler" is shorthand for calling <code>p.then(fulfillmentHandler, rejectionHandler)</code>, using the initial value of <a href="https://tc39.github.io/ecma262/#sec-promise.prototype.then"><code>Promise.prototype.then</code></a>.

**Comment by kenchris** [comment]
Not exactly sure how the new wording should be @domenic

**Comment by domenic** [comment]
Sorry about this; we just fixed that with https://github.com/heycam/webidl/pull/792. You can now use "react to _promise_".
