### ISSUE TITLE
After removing special record, get rid of Web NFC message terminology

### ISSUE THREAD

**Issue by kenchris** [w3c-cg/web-nfc#343]
We can just use "NDEF message".

**Comment by zolkis** [comment]
Right.

**Comment by zolkis** [comment]
I suggest we keep the "Web NFC message" around for a little longer, until we figure out what policies the Web NFC spec will impose on encoding, case sensitivity, etc. That is, until we define what interoperability means between Web NFC implementations vs with any other NFC device.
