### ISSUE TITLE
ID field is called Message Identifier in NFC specs

### ISSUE THREAD

**Issue by kenchris** [w3c-cg/web-nfc#344]
But it is a bit confusing at it is per record.

It might be that there is only one id allowed per NDEF message, but I didn't see that in the specs.

We can call it record id and add a note about the name in the NFC specs.

**Comment by zolkis** [comment]
The NDEF spec uses the term "message identifier" only in one place, in the context of the ID of a record, which in many other places is referred to as "payload id".

I am fine to use "record id", especially since it can be present while payload still missing.
