### ISSUE TITLE
Data Mapping part is missing toRecords()

### ISSUE THREAD

**Issue by leonhsl** [w3c-cg/web-nfc#354]
With the description in https://w3c.github.io/web-nfc/#the-ndefrecord-interface:
> external
If the recordType value is an external type, then return the result of running parse records from bytes on bytes.
Otherwise, return null.

`toRecords()` should be only available for external type records, which should be clear in [Data Mapping](https://w3c.github.io/web-nfc/#data-mapping).

**Comment by kenchris** [comment]
It should always be available but might just return null.

It should also return valid values for Sp smart poster and potentially other well-known records

**Comment by kenchris** [comment]
The `toRecords` is also not a link, which it should be.

Also, the following won't work for Sp:

![image](https://user-images.githubusercontent.com/1101339/65875883-7cc73c00-e388-11e9-8eb7-b6a42413bf90.png)

@zolkis

**Comment by zolkis** [comment]
Partly fixed by #359 and I added the missing row in Data mapping in #361

**Comment by kenchris** [comment]
What is missing @zolkis

**Comment by zolkis** [comment]
It should be fine now.
