### ISSUE TITLE
website is not a thing

### ISSUE THREAD

**Issue by annevk** [w3c-cg/web-nfc#36]
Please make sure everything you say is established in first principles.

**Comment by kenchris** [comment]
What is the right term? web page?

**Comment by annevk** [comment]
I think often you mean to say browsing context (or address some part of that concept).

**Comment by annevk** [comment]
Note that the same goes for "web app". E.g., "web app's document URL" is pure fiction. Where is it defined that a "web app" has a document URL? And what does that mean?

**Comment by zolkis** [comment]
Yeah, these are more colloquial than standardized/canonical names, even though are defined terms. Would be good to use one terminology - suggestions?

**Comment by annevk** [comment]
Well, you basically want to look at what these map to in an implementation and where the concepts are defined that this implementation already has. Typically that means studying the HTML Standard.

**Comment by kenchris** [comment]
Seems pretty fitting:

http://www.w3.org/TR/html5/browsers.html#windows

A browsing context is an environment in which Document objects are presented to the user. Note: A tab or window in a Web browser typically contains a browsing context, as does an iframe or frames in a frameset.

**Comment by jyasskin** [comment]
Here's a first cut at replacing uses of websites in the NFC spec: 
1. The uses in http://w3c.github.io/web-nfc/index.html#reading-nfc-tags are fine: they're non-normative and can use colloquial language.
2. For "a website must be visible and in focus", copy wording from http://www.w3.org/TR/page-visibility/, or just refer to its terms.
3. For 'only websites with a schema starting with "https://"', write it into the algorithms instead. https://webbluetoothcg.github.io/web-bluetooth/#requestDevice-secure-context has an example.

**Comment by kenchris** [comment]
Thanks a lot for these pointers @jyasskin !
