### ISSUE TITLE
Why returning null in arrayBuffer() from text, URL, and external record type?

### ISSUE THREAD

**Issue by beaufortfrancois** [w3c-cg/web-nfc#371]
Spec currently says for `arrayBuffer()`:
> 1. If the recordType value is equal to "json" or "opaque", then return an ArrayBuffer whose contents are the bytes. Re-throw any exceptions.
> 2. Otherwise, return null.

I'm not sure to understand why we should return `null` for text, url, and external record types. I think `arrayBuffer()`should always return raw bytes and let web developers handle those as they're explicitly asking for it.

**Comment by kenchris** [comment]
I tend to agree. Earlier it wasn't possible the way the spec was written, but I think it is now.

For instance text was an issue because we parsed the bytes earlier, but we don't do that anymore

**Comment by beaufortfrancois** [comment]
Do you want me to send a PR?

**Comment by kenchris** [comment]
Sure
