### ISSUE TITLE
Consider renaming NFCReader etc to NDEFReader

### ISSUE THREAD

**Issue by kenchris** [w3c-cg/web-nfc#388]
After looking at the Core NFC API, I see that they split out the handling of each type, like NDEFSession and NFCTagSession.

I think it is wise for us to do the same, as that would allow us to add NFCTagReader (or NFCTagTechReader) in the future without risking that we have to change the existing API

**Comment by beaufortfrancois** [comment]
Big +1 to this!

**Comment by kenchris** [comment]
Let's do it!
