### ISSUE TITLE
local type are well-known not external

### ISSUE THREAD

**Issue by kenchris** [w3c-cg/web-nfc#390]
This is wrong

![image](https://user-images.githubusercontent.com/1101339/67083600-b925d500-f19b-11e9-9658-b390bb66a852.png)

**Comment by beaufortfrancois** [comment]
WIP

**Comment by kenchris** [comment]
I just started fixing this, sorry. Uploaded PR now so you can check and maybe we can land that part. Then I can clean up the next table

**Comment by beaufortfrancois** [comment]
I'll review https://github.com/w3c/web-nfc/pull/394 and we'll see  if there's anything left in https://github.com/w3c/web-nfc/pull/395
