### ISSUE TITLE
Find a new name for MIME media-type records

### ISSUE THREAD

**Issue by beaufortfrancois** [w3c-cg/web-nfc#393]
https://github.com/w3ctag/design-principles/issues/140#issuecomment-543690443 suggests we should not use "media" for MIME media-type NDEF records. So let's pick another one:

- [ ] "geezer"
- [ ] "iana-media"
- [ ] "media-type"
- [x] "mime"
- [ ] "mime-data"
- [ ] "mime-media"
- [ ] "mime-type"
- [ ] "mime-typed-data"
- [ ] "typed-data"

This list is not exhaustive. Feel free to add your suggestions.

**Comment by kenchris** [comment]
Android uses MIME media in documentation and in some of the enums

**Comment by zolkis** [comment]
I think "`mime`" is short and closest to the NDEF terminology, so I vote on that.

**Comment by beaufortfrancois** [comment]
I'd go with `"mime"` as well.

**Comment by zolkis** [comment]
OK. Let's work with this name for a while and consider others in the meantime.
