### ISSUE TITLE
Missing some record types in the algo creating ndef messages

### ISSUE THREAD

**Issue by leonhsl** [w3c-cg/web-nfc#408]
https://w3c.github.io/web-nfc/#creating-ndef-message needs to be updated to handle all possible record types, at least "smart-poster" and "absolute-url" are missing now.

**Comment by zolkis** [comment]
Also, we need to provide algorithms to match external type and local type.

**Comment by zolkis** [comment]
Also, we need algo for creating signature records, if we support that (see #363 for challenges).
Then only handover records are missing, should we support creating (and reading) them, too (as data)?

**Comment by zolkis** [comment]
Algorithms for matching external and local types are in place now. Absolute-URL is missing.
Also, we need to complete the "parse Sp" steps (and modify the "parse record from bytes" on the way).
Filing separate issues to track these.
