### ISSUE TITLE
What's the definition of "a standard local type to smart poster or a handover record"?

### ISSUE THREAD

**Issue by leonhsl** [w3c-cg/web-nfc#409]
5.2 of https://w3c.github.io/web-nfc/#dfn-map-local-type-to-ndef:

> If record's recordType is a standard local type to smart poster or a handover record, then set ndefRecord's TNF field to 1 (well-known type record), otherwise set ndefRecord's TNF field to 4 (external type record).

`recordType` is just a text starting with a lower case character or a number, how could we check whether it's `a standard local type to smart poster or a handover record`? There is no definition for `a standard local type to smart poster or a handover record` in the spec.

**Comment by zolkis** [comment]
The standard local types for smart-poster and handover types (which we don't use for now) are enumerated in [this section](https://w3c.github.io/web-nfc/#well-known-type-records-tnf-1).
Should we have explicit algorithm to match external/standard local/local types?

**Comment by leonhsl** [comment]
> Examples: "T" for text, "U" for URL, "Sp" for smart poster, "Sig" for signature, "Hc" for handover carrier, "Hr" for handover request, "Hs" for handover select, etc.

Do you mean the above enumeration? They are NOT local type names.

**Comment by zolkis** [comment]
No, I meant the `s`, `t` and `act` in `smart-poster` context, but they may be reused in other context with different meaning. The work "standard" doesn't really mean anything normative here, it's like NFC Forum used a few local types that are called "standard" local types.

The checking should be like
- if a string is a match for being external type, then it is
- otherwise, if a string is a match for being any local type (basically just starting with lowercase) and the context exists (currently: it is defined inside a message that is payload to another record), then it is local type
- otherwise no match, error.

What concerns the text in the subject, read it in two parts:
1. a standard local type to smart poster
2. or a handover record.

**Comment by leonhsl** [comment]
Sure we just treat it as an external type record if the type string matches the rule of external types, no matter it's in an embedded context or not.

The question is for the following step, how could we tell it should be converted to external type record (TNF=4) or well-known type record (TNF=1)?
> otherwise, if a string is a match for being any local type (basically just starting with lowercase) and the context exists (currently: it is defined inside a message that is payload to another record), then it is local type

Probably the only case for TNF=1 should just be "the s, t and act in smart-poster", and handover types (we don't use now)? All other cases go with TNF=4?
But, from https://developer.android.com/reference/android/nfc/NdefRecord.html#TNF_WELL_KNOWN, it looks like Android API does not include "the s, t and act in smart-poster" in the scope of TNF=1, i.e. no RTD_XXX definition for "the s, t and act in smart-poster".

**Comment by zolkis** [comment]
So yes, the only TNF=1 are the `s`, `t` and `act` (local) type records that are inside the context of a TNF=1 "Sp" record. All the others are TNF=4.
Handover records are TNF=1 but ATM we don't support them.

It is important to emphasize that from name/string matching point of view, local type names are not a subset of external type names. Strings that match as external types are not treated as local types,
and (remaining) local types are not a match for the external type. So they are disjunct. 

But the local type _records_ (in a message) may be hosted by external type _records_ :).

**Comment by kenchris** [comment]
Local types means that types that are restricted to a certain other type of record. As they (their names and behavior) are restricted they don't need any namespacing as their names/types can be used inside other records with totally other meaning and data payload

**Comment by beaufortfrancois** [comment]
See https://github.com/w3c/web-nfc/pull/411

**Comment by kenchris** [comment]
Can we close?
