### ISSUE TITLE
android.nfc.NdefRecord.createXXX() does not have a parameter for record's id

### ISSUE THREAD

**Issue by leonhsl** [w3c-cg/web-nfc#410]
In our impl, we use android.nfc.NdefRecord.createXXX() helper functions to construct {Text,Uri,Mime,External} records then write them into nfc tags, as we want to write the record's id now, we found that these helper functions do not allow us to pass any id information.

We can switch to use NdefRecord ctor which can accept the id, but it lacks lots of checks those helpers do. Any good idea for this? @beaufortfrancois @reillyeon @riju

**Comment by zolkis** [comment]
IMHO the only way Android allows us is to use the low-level constructors and do the checks ourselves (i,e, fully manual mode).

**Comment by kenchris** [comment]
That also seems pretty fine. It gives us a lot of flexibility and it is easier to make sure that no "magic" happens in those methods that actually makes up not compatible with the spec.

I think it would be good to check what checks those helpers do. Maybe we miss something in the spec, or maybe they are just obvious checks that we should also do in our implementation

**Comment by beaufortfrancois** [comment]
Yes, we should not rely on those helper functions. For info, I've started to bypass `createTextRecord` for instance in https://chromium-review.googlesource.com/c/chromium/src/+/1876390/6/services/device/nfc/android/java/src/org/chromium/device/nfc/NdefMessageUtils.java

**Comment by kenchris** [comment]
Guess we can close?
