### ISSUE TITLE
Wrong Absolute-URL recordType in Data Mapping?

### ISSUE THREAD

**Issue by beaufortfrancois** [w3c-cg/web-nfc#414]
I think `recordType` in https://w3c.github.io/web-nfc/#data-mapping should be "absolute-url" instead of "url" for TNF Field set to 3. Is that right or am I missing something?

![image](https://user-images.githubusercontent.com/634478/67657845-3ac5f180-f958-11e9-8989-0b6d06ca78be.png)

**Comment by beaufortfrancois** [comment]
I'm happy to send a PR to fix it if needed,

**Comment by zolkis** [comment]
That's right, how come it's not `"absolute-url"`... grrr...
