### ISSUE TITLE
Spec disagrees with Security section

### ISSUE THREAD

**Issue by zolkis** [w3c-cg/web-nfc#420]
The latest spec changes go against some statements in the [Security](https://w3c.github.io/web-nfc/#security-and-privacy) section.
Needs a complete overhaul, especially [Security policies](https://w3c.github.io/web-nfc/#security-policies), especially [storing site URL in record id](https://w3c.github.io/web-nfc/#store-site-url-as-record-identifier-when-writing-data).

**Comment by zolkis** [comment]
We could also move the Security section to the end and at that, move out IDL index and Acknowledgement from under the previous section (alignment mismatch, see Table of Contents).

**Comment by beaufortfrancois** [comment]
@zolkis Can you tackle this?

**Comment by zolkis** [comment]
Yes, it's under work, with security people.

**Comment by zolkis** [comment]
Related: #363 
Also: #438

**Comment by zolkis** [comment]
Fixed by #440
