### ISSUE TITLE
Parse unknown records to mime records?

### ISSUE THREAD

**Issue by beaufortfrancois** [w3c-cg/web-nfc#421]
Do we intend to parse "unknown" records to "mime" records or is this a typo?

![image](https://user-images.githubusercontent.com/634478/67750845-4b499b00-fa30-11e9-89c0-b329bb879fd5.png)

**Comment by zolkis** [comment]
This was relevant when we treated unknown records as `application/octet-stream`, but that has recently changed :).

So I guess it belongs to the cleanup after the change.

**Comment by beaufortfrancois** [comment]
Do you confirm that the record's recordType should be "unknown" now?
I'm happy to open a PR to fix it.

**Comment by zolkis** [comment]
Right, `recordType` should be `"unknown"` and `mediaType` should be `undefined`.
Thanks for noticing.
