### ISSUE TITLE
Remove NDEFPushOptions ignoreRead

### ISSUE THREAD

**Issue by beaufortfrancois** [w3c-cg/web-nfc#424]
It seems like the NDEFPushOptions `ignoreRead` could easily be replaced with NOT listening to the `onreading` event as you can see below.

If that's the case, shall we simply remove it?

```js
const reader = new NDEFReader();
reader.scan();
reader.onreading = event => { /* Won't be called because ignoreRead is true */ };

const writer = new NDEFWriter();
await writer.push('hello world', { ignoreRead: true });
```
and its equivalent
```js
const reader = new NDEFReader();
reader.scan();

const writer = new NDEFWriter();
await writer.push('hello world');
reader.onreading = event => { /* Will be called after write happened if needed */ };
```

**Comment by zolkis** [comment]
Makes sense to me.

**Comment by kenchris** [comment]
The feedback we got from users is that the reading and writing code often lives in very different part of the application, like even in my shopping demo, the writer is inside a dialog and the reader is part of the list view.

**Comment by zolkis** [comment]
Do we go ahead with removing `ignoreRead`?

**Comment by beaufortfrancois** [comment]
@kenchris Which changes would be required for your shopping demo for instance to handle this? Would this be that hard?

I'm trying to understand whether `ignoreRead` is convenient thing like we used to have with `toJSON`, etc. or if that's something web developers can't work without (or at least will have trouble with).

**Comment by kenchris** [comment]
I find it annoying if not there. It will force me to handle all NFC in one place so basically create a singleton service.

The cost of having it is quite small

**Comment by beaufortfrancois** [comment]
Argh! I'm torn ;)

On one hand, like you're saying, the cost of having it is quite small.
On the other hand, I feel like web developers would know how to do deal with this quite easily.
Even in your dialog case, it seems OK:

```js
const dialog = document.querySelector('dialog');

const observer = new MutationObserver(mutations => {
  myNdefReader.onreading = (mutations[0].target.open) ? null : onReading;
});
observer.observe(dialog, { attributeFilter: [ 'open' ] });

**Comment by kenchris** [comment]
You assume that people deal with reading and writing in the same code and same UI parts, but that is seldom the case... It might even be done by different teams and even libraries in top

What you have above looks like a hack that could easily break if all the code isn't written by the same person

**Comment by zolkis** [comment]
The use case seems to be that a writer could disable all reads for a given push. That would make `ignoreRead` global. However, we have a conflict between step 7.1 of [push()](https://w3c.github.io/web-nfc/#steps-push) and the [listening algorithm](https://w3c.github.io/web-nfc/#listening-for-content) saying 

> If there are any NDEFReader instances in activated reader objects then the UA MUST listen to NDEF messages on all connected NFC adapters.

**Comment by zolkis** [comment]
BTW while checking this I realized we should check all occurrences of "NFC adapter" through the spec and make sure the parallel operation vs error reporting (for one or more adapters) is consistent.

**Comment by zolkis** [comment]
See #494 .

**Comment by zolkis** [comment]
Can we close (with #494 being merged)?

**Comment by kenchris** [comment]
Let's close this
