### ISSUE TITLE
What is the correct way to check whether the browser supports Web NFC API or not?

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [w3c-cg/web-nfc#434]
What is the correct way to check whether the browser supports Web NFC API or not?

In the previous version of API, I've used the following:

```js
if ('nfc' in navigator) {
  // use Web NFC API
}
```

Is

```js
if ('NDEFReader' in window && 'NDEFWriter' in window) {
  // use Web NFC API
}
```

the correct way?

It would also really nice to have a property (or something) to check whether the device has NFC chip or not.

**Comment by FluorescentHallucinogen** [comment]
Are there NFC chips that support only reading, but not writing NFC tags? If yes, how to detect this?

**Comment by beaufortfrancois** [comment]
Indeed!
```js
if ('NDEFReader' in window) { /* ... Scan NDEF Tags */ }
if ('NDEFWriter' in window) { /* ... Write NDEF Tags */ }
```
You can also use Permissions API
```js
try {
  const status = await navigator.permissions.query({ name: 'nfc'});
}
catch(e) {
  // No Web NFC support
}
```

**Comment by beaufortfrancois** [comment]
To check whether the device has NFC chip or not, you can call `scan()` or `push()`and it will reject with an appropriate error if that's the case.

**Comment by beaufortfrancois** [comment]
> Are there NFC chips that support only reading, but not writing NFC tags? If yes, how to detect this?

I don't think so.

**Comment by FluorescentHallucinogen** [comment]
@beaufortfrancois What about adding this to the spec?

**Comment by beaufortfrancois** [comment]
Which parts?

Good luck for your [talk](https://twitter.com/GDGNsk/status/1187389660462485505) by the way ;)

**Comment by FluorescentHallucinogen** [comment]
@beaufortfrancois 
> Good luck for your talk by the way ;)

Thanks! This is workshop, not talk. :)

> Which parts?

About browser feature detection: https://github.com/w3c/web-nfc/issues/434#issuecomment-549765910.

**Comment by beaufortfrancois** [comment]
I'll do this.
Feel free to file more issues as you play with Web NFC.
Note that current Chromium implementation doesn't show prompts yet, but will really soon.

**Comment by FluorescentHallucinogen** [comment]
> Note that current Chromium implementation doesn't show prompts yet, but will really soon.

I [know](https://chromium.googlesource.com/chromium/src.git/+/51f9ee3727aefb076947fe6ab58154f479bc30d3). :) Thanks!

**Comment by beaufortfrancois** [comment]
Cool!
You can check WIP at https://chromium-review.googlesource.com/q/hashtag:%22webnfc%22+(status:open%20OR%20status:merged)

**Comment by FluorescentHallucinogen** [comment]
@beaufortfrancois Just curious, what if I call `navigator.permissions.query({ name: 'nfc'})`, but NFC is disabled in the OS settings? Does your CL cover this use case similar to the following (example for Web Geolocation API)?

![1](https://user-images.githubusercontent.com/7892779/68206457-c9341600-ffdd-11e9-854c-49ca0b3c0955.png)
![2](https://user-images.githubusercontent.com/7892779/68206462-cb967000-ffdd-11e9-8938-85f975a43d34.png)
![3](https://user-images.githubusercontent.com/7892779/68206466-cdf8ca00-ffdd-11e9-8e43-512fa48aa280.png)
![4](https://user-images.githubusercontent.com/7892779/68206471-d05b2400-ffdd-11e9-9cbc-02e39dbac484.png)

**Comment by beaufortfrancois** [comment]
`navigator.permissions.query({ name: 'nfc'})` will resolve with a status of "denied".

```js
navigator.permissions.query({ name: "nfc" }).then(permissionStatus => {
  console.log(`NFC user permission: ${permissionStatus.state}`);
  permissionStatus.onchange = _ => {
    console.log(`NFC user permission changed: ${permissionStatus.state}`);
  };
});
```

**Comment by beaufortfrancois** [comment]
https://w3c.github.io/web-nfc/#feature-support has been added to the spec.

**Comment by FluorescentHallucinogen** [comment]
@beaufortfrancois 
> `navigator.permissions.query({ name: 'nfc'})` will resolve with a status of "denied".

Silently? It would be great to let the user know what went wrong and provide the ability to enable NFC in the OS settings (see screenshots in https://github.com/w3c/web-nfc/issues/434#issuecomment-549795888).

P.S. Sorry for offtopic.

**Comment by beaufortfrancois** [comment]
`navigator.permissions.query` will always be silent.  What we could use is `navigator.permissions.request`, however it is not functional at the moment in Chromium.

Having something similar to Geolocation makes sense to me.
I'll ping appropriate folks. Thanks!

**Comment by FluorescentHallucinogen** [comment]
@beaufortfrancois 

Just to clarify, will there be a separate permission prompt for writing NFC (alongside permission prompt for reading NFC) or one single permission prompt for the whole Web NFC API (both reading and writing)?

Use case: what if I want to allow the web app to only read NFC tags but not write?

I'm not familiar with the process of merge code in Chromium. I see that the NFC permission change [was merged](https://chromium-review.googlesource.com/q/hashtag:%22webnfc%22), but I've just tested in Chrome Canary for Android with `chrome://flags/#enable-webnfc` flag enabled today and for some reason don't see the permission prompt. Why? Any ETA?

**Comment by beaufortfrancois** [comment]
> Just to clarify, will there be a separate permission prompt for writing NFC (alongside permission prompt for reading NFC) or one single permission prompt for the whole Web NFC API (both reading and writing)?

In Chromium, there will be one single permission prompt for using the Web NFC API.

> I'm not familiar with the process of merge code in Chromium. I see that the NFC permission change [was merged](https://chromium-review.googlesource.com/q/hashtag:%22webnfc%22), but I've just tested in Chrome Canary for Android with `chrome://flags/#enable-webnfc` flag enabled today and for some reason don't see the permission prompt. Why? Any ETA?

I'm currently working on making sure tests pass for https://chromium-review.googlesource.com/c/chromium/src/+/1895345. Once it's solved, it will be pushed to Chromium. I hope this will be done this week or next week.

**Comment by FluorescentHallucinogen** [comment]
@beaufortfrancois
> In Chromium, there will be one single permission prompt for using the Web NFC API.

Any plans to separate permission prompts for reading and writing?

From the name of https://chromium-review.googlesource.com/c/chromium/src/+/1895345 — `[WebNFC] Add permission prompt for NDEFWriter.push` it's not clear is this for writing only?

What if I try to read NFC tags (if user didn't previously allow Web NFC), will the permission prompt be shown?

**Comment by beaufortfrancois** [comment]
> @beaufortfrancois
> 
> > In Chromium, there will be one single permission prompt for using the Web NFC API.
> 
> Any plans to separate permission prompts for reading and writing?

Nope. Not in Chromium.

> From the name of https://chromium-review.googlesource.com/c/chromium/src/+/1895345 — `[WebNFC] Add permission prompt for NDEFWriter.push` it's not clear is this for writing only?
> 
> What if I try to read NFC tags (if user didn't previously allow Web NFC), will the permission prompt be shown?

Yup. Once user approves Web NFC, prompt won't be shown anymore.

**Comment by beaufortfrancois** [comment]
For info, I'm currently adding "second" prompt to Chrome to turn on NFC if needed. See https://chromium-review.googlesource.com/c/chromium/src/+/1940241

![image](https://user-images.githubusercontent.com/634478/69873470-b816b600-12b8-11ea-8da1-d63145c4a7c5.png)

**Comment by beaufortfrancois** [comment]
@FluorescentHallucinogen All bits have finally [landed](https://chromiumdash.appspot.com/commits?user=beaufort.francois%40gmail.com&platform=Android) in Chrome Canary for Android. You can give it a try at https://permission.site

<img src="https://user-images.githubusercontent.com/634478/71075694-d0c20f80-2184-11ea-8911-d8e13bedebe2.png" width="24%"> <img src="https://user-images.githubusercontent.com/634478/71075752-e59ea300-2184-11ea-9ad6-f2018fd12cdf.png" width="24%"> <img src="https://user-images.githubusercontent.com/634478/71075759-e8999380-2184-11ea-9fcf-e853b83774e1.png" width="24%"> <img src="https://user-images.githubusercontent.com/634478/71075768-eb948400-2184-11ea-986c-1889d58d9635.png" width="24%">

**Comment by FluorescentHallucinogen** [comment]
@beaufortfrancois That's awesome! Thanks for your work!

One detail: what about changing the word "phone" in texts to more generic "device"? What if my device is e.g. tablet, not phone?

**Comment by beaufortfrancois** [comment]
@FluorescentHallucinogen I'll share this feedback with the team. Thanks!

**Comment by FluorescentHallucinogen** [comment]
@beaufortfrancois Any plans on Origin Trial for Web NFC API?

**Comment by riju** [comment]
@FluorescentHallucinogen : We are planning for M81, so around end of Jan '20.

**Comment by beaufortfrancois** [comment]
To know more about the Origin Trial for Web NFC, I'd recommend having a look at https://web.dev/nfc/
