### ISSUE TITLE
obtain reading and push permission should be the same

### ISSUE THREAD

**Issue by beaufortfrancois** [w3c-cg/web-nfc#438]
I'm not sure why but "[obtain reading permission](https://w3c.github.io/web-nfc/#dfn-obtain-reading-permission)" and "[obtain push permission](https://w3c.github.io/web-nfc/#dfn-obtain-push-permission)" are different. I think both should be the same and consolidated under a unique "obtain nfc permission".

What are your thoughts?

**Comment by zolkis** [comment]
Isn't pushing more powerful feature than reading? 

I think originally the idea was that reading policy could be more relaxed than writing policy.

Especially with signature records, we could apply browser origin policies against the URLs contained in the cert chain and/or the URL record in the message. I guess read and write scenarios could undergo different policies?

**Comment by riju** [comment]
my 2 cents: NFC read and write should be the same permission at least say Chrome's PoV, maybe we can add a note that implementer is free to have a choice but the first implementer Chrome is going to use same `nfc` permission

**Comment by kenchris** [comment]
Permission allow to have options along with them no? If so, it can always be extended

For instance Web USB uses the following descriptor:

![image](https://user-images.githubusercontent.com/1101339/68381663-821b6180-0152-11ea-902d-1ad3b4b85d36.png)

We could always add options like "write: true" there if that ever became needed

**Comment by zolkis** [comment]
Fixed by #440

**Comment by zolkis** [comment]
Can we close this?

**Comment by beaufortfrancois** [comment]
I think so.
