### ISSUE TITLE
Problems in '9.10.1 Creating NDEF message'

### ISSUE THREAD

**Issue by leonhsl** [w3c-cg/web-nfc#443]
https://w3c.github.io/web-nfc/#creating-ndef-message
  1.  lacks descriptions about how to wrap a `DOMString` or `BufferSource` to create an `NDEFMessage`.
  2. 4.3 description is wrong:

> If message is of type NDEFMessageInit and its id is not null:
  
  3. It seems to me the spec wants to say `NDEFRecord#id` is null when `NDEFRecordInit#id` is not provided, if so, please change `NDEFRecord` interface definition to reflect it, i.e. add '?' suffix.

**Comment by beaufortfrancois** [comment]
Thank you for raising these issues.
I'll open a PR to address those shortly.
