### ISSUE TITLE
Keep (how?) or remove the record id?

### ISSUE THREAD

**Issue by leonhsl** [w3c-cg/web-nfc#445]
This issue comes from the discussion at https://github.com/w3c/web-nfc/pull/444#discussion_r349416140

**Comment by leonhsl** [comment]
As we've already been making WebNFC kind of a low-level API so it's good to abandon all those 'smartness' left from the old era, like binding record ids with the hostname of the current web page.

+1 to the following suggestion from @beaufortfrancois 

> I'd be in favor of removing this "id" constraint algorithm and let web developers do what ever they want with it.

const writer = new NDEFWriter();
await writer.push({ records: [{ recordType: 'text', data: 'hi', id: '123' }] });
...
const reader = new NDEFReader();
await reader.scan({id: '123' });
reader.onreading = event => {};

**Comment by beaufortfrancois** [comment]
If we all agree on removing constraint on record id, I'll assign the task of updating the spec to myself.

**Comment by beaufortfrancois** [comment]
I've started updating spec at https://github.com/w3c/web-nfc/pull/446

**Comment by beaufortfrancois** [comment]
@leonhsl Let us know if that looks good to you.
