### ISSUE TITLE
Remove NDEFRecord.[[PayloadData]] internal slot

### ISSUE THREAD

**Issue by Honry** [w3c-cg/web-nfc#447]
As now we have NDEFRecord.data that already handles bytes of payload data, we can directly remove the NDEFRecord.[[PayloadData]] internal slot and use NDEFRecord.data instead.

**Comment by beaufortfrancois** [comment]
True! Thank you @Honry!
@zolkis Can you update spec?

**Comment by zolkis** [comment]
As long as the DataView covers the whole payload data, we can do that. IoW, yes.
