### ISSUE TITLE
Do not use 'any' to define NDEFRecordInit#data

### ISSUE THREAD

**Issue by leonhsl** [w3c-cg/web-nfc#453]
I remember someone before gave a comment about not using `any` as possible as we can when doing Web IDL design, but I can not point out the exact place now.

Based on that I'd propose changing `NDEFRecordInit#data` from `any` type to
`typedef (DOMString or BufferSource or NDEFMessageInit) NDEFRecordDataSource;`,
which should just be enough. (See https://w3c.github.io/web-nfc/#data-mapping)

@reillyeon @riju @beaufortfrancois @zolkis @kenchris

**Comment by beaufortfrancois** [comment]
That looks good to me. I'll draft a PR.

**Comment by beaufortfrancois** [comment]
PR is available at https://github.com/w3c/web-nfc/pull/454.
Please have a look.
