### ISSUE TITLE
Tag with 'NFC-A' and 'ISO-DEP' technologies but not recognized as ndef-compatible

### ISSUE THREAD

**Issue by Honry** [w3c-cg/web-nfc#459]
I have a tag (see following image read from native nfc app), with 'NFC-A' and 'ISO-DEP' technologies and no NDEF message, which is type of NFC Forum Type 4, per spec https://w3c.github.io/web-nfc/#ndef-compatible-tag-types, my tag should be one of ndef compatible tag types, but which couldn't be read/write from both native nfc app or Chrome, when writing with native nfc app, it throws with "Non-ndef compatible" error. 

![WeChat Image_20191108154518](https://user-images.githubusercontent.com/3271201/70037233-32b13f80-15f1-11ea-86e2-fca170a3ff59.jpg)

**Comment by leonhsl** [comment]
By my understanding, this tag should just be ndef compatible because of the `NfcA` technology it carries.

Could anyone help clarify the phenomenon here?

**Comment by kenchris** [comment]
Is is formatted as ndef?

**Comment by Honry** [comment]
No, it could not be formatted as ndef.

**Comment by zolkis** [comment]
AFAIK they MAY also expose NDEF, but not required to do so.

**Comment by Honry** [comment]
So a tag is of NFC Forum Type 4 may be NDEF compatible, but a tag without NDEF technology (e.g. my tag with only "NFC-A" and "ISO-DEP" technologies) must be NDEF non-compatible, right?

**Comment by kenchris** [comment]
as far as I understand all NFC tags should support ndef, but I might be wrong - or this might be an issue with the tag. But as this is outside our scope I am closing
