### ISSUE TITLE
NDEFRecord.data should return null rather than undefined

### ISSUE THREAD

**Issue by Honry** [w3c-cg/web-nfc#462]
In following algorithms,
> 9.11.9.6 Parsing NDEF MIME type records
9.11.9.8 Parsing NDEF external type records
9.11.9.9 Parsing NDEF unknown type records

Spec says:
>  Let buffer be the byte sequence of ndefRecords's PAYLOAD field if that exists, or otherwise undefined.
Set record's data to buffer.

But per discussion in https://github.com/w3c/web-nfc/pull/441,  `null` is a more correct falsey value than `undefined` for an interface type.

Besides, setter of record's data is missing in empty record type's parser algorithm.

**Comment by beaufortfrancois** [comment]
Thanks @Honry for raising this issue!
I'll open a PR to fix this soon.

**Comment by beaufortfrancois** [comment]
I've just opened https://github.com/w3c/web-nfc/pull/463
