### ISSUE TITLE
Simplify creating external records

### ISSUE THREAD

**Issue by zolkis** [w3c-cg/web-nfc#470]
Following the discussion [here](https://github.com/w3c/web-nfc/pull/467#discussion_r357220894).

@beaufortfrancois: 
> Thinking about it again, I don't think Web NFC should be smart and use the effective domain of the origin as domain name in external type names when creating/reading external type records.
I would argue web developers should always set the full external type record. Think about staging environments, where `staging.example.com:smart-poster` would be written automatically if `:smart-poster` were to be allowed. It would not match when read in a prod environment.

So the proposal is to validate input for external type as follows:
- find the last occurrence of `:`; 
- the part after it should validate as an external type
- the part before it has to be a domain name that should be validated by the [valid domain](https://url.spec.whatwg.org/#valid-domain) steps from the URL Standard (thanks @kenchris for the pointer).

**Comment by kenchris** [comment]
You might need to use this instead https://url.spec.whatwg.org/#host-parsing

**Comment by kenchris** [comment]
Just doing this on the remaining string should probably be fine:

![image](https://user-images.githubusercontent.com/1101339/70804338-815f9600-1db6-11ea-9ec4-b68b642edfa3.png)
