### ISSUE TITLE
NDEFRecordInit#recordType is a required field

### ISSUE THREAD

**Issue by leonhsl** [w3c-cg/web-nfc#497]
Means `NDEFRecordInit#recordType` is never `undefined`, so step 1 of https://w3c.github.io/web-nfc/#creating-ndef-record should be removed.

**Comment by zolkis** [comment]
In the same round, fix the comments from [here](https://github.com/w3c/web-nfc/commit/66ea476f72029403814736a7e22be962ad5a8c59).

**Comment by zolkis** [comment]
@leonhsl PTAL
