### ISSUE TITLE
Add note about Web NFC conventions

### ISSUE THREAD

**Issue by beaufortfrancois** [w3c-cg/web-nfc#504]
@zolkis [said](https://github.com/w3c/web-nfc/pull/502#pullrequestreview-337667570):
> I suggest adding a Note or other clarification (at your discretion) that summarizes what new conventions Web NFC is making about type names vs the NFC Forum standardized type names.

**Comment by beaufortfrancois** [comment]
Shall we include more in this table?

### Differences between NFC Forum and Web NFC

| Record type name | NFC Forum (Type field) | Web NFC (recordType) |
| - | - | - |
Text record | `T` | `text` 
URL record | `U` | `url` 
Smart poster record | `Sp` | `smart-poster` 
Local record (example) | `act` | `:act`
Empty record | | `empty`

**Comment by zolkis** [comment]
Nice, thanks! We should also add `t` vs `:t` for smart poster local type "type" record, and `s` vs `:s` for local type "size" record. Title could perhaps be "Mapping between NFC Forum standard types and Web NFC type names" or similar?

**Comment by kenchris** [comment]
This is only mapping of the subset "well known types" and their encoding. NFC has additional types, like absolute url, external etc

**Comment by zolkis** [comment]
Right, actually we could embed/merge that table with the tables in [Data mapping](https://w3c.github.io/web-nfc/#data-mapping).

**Comment by beaufortfrancois** [comment]
@zolkis I've followed your advice. See https://github.com/w3c/web-nfc/pull/506
