### ISSUE TITLE
Create per-origin NFC adapter properties section?

### ISSUE THREAD

**Issue by zolkis** [w3c-cg/web-nfc#51]
Like in the [Bluetooth spec](https://webbluetoothcg.github.io/web-bluetooth/#per-origin-device-properties)?

Or is the current way of specifying behavior in [algorithmic steps](http://rawgit.com/zolkis/web-nfc/gh-pages/index.html#dom-nfc-requestadapter) good enough?
Affected properties would be (per origin and per NFC adapter):
- suspended state (depends on visibility and focus of the Window of the Document of the script execution environment)
- push timer
- push buffers for tags and peers
- receive buffer.

**Comment by jyasskin** [comment]
Are those properties shared between multiple execution environments within the same origin?

**Comment by zolkis** [comment]
No, they are not. There are different suspended states, different timers, and push buffers. Receive buffer may be shared, but it's implementation detail. In fact all these are local private to implementations.

**Comment by jyasskin** [comment]
Then these properties wouldn't go in a per-origin section. It might make sense to describe some of these (push and receive buffers) as [internal slots](https://webbluetoothcg.github.io/web-bluetooth/#terminology) of the adapter within the execution environment, and the suspended state could just come out of how the algorithms react to an unfocused browsing context.

**Comment by zolkis** [comment]
#50 fixes this by introducing internal slots.
