### ISSUE TITLE
NDEFRecordInit#encoding should be only for BufferSource data source

### ISSUE THREAD

**Issue by leonhsl** [w3c-cg/web-nfc#521]
https://w3c.github.io/web-nfc/#mapping-string-to-ndef needs to be refined.

If the data source is a string, we always get its `utf-8` bytes and write as the payload, i.e. `encoding` is forcibly set to "utf-8".

`NDEFRecordInit#encoding` is only used for WebDevs to declare how the `BufferSource` data is encoded.

**Comment by beaufortfrancois** [comment]
You're right. I'll fix this.

**Comment by leonhsl** [comment]
Should we throw an error if `NDEFRecordInit#encoding` is neither 'utf-8' nor `undefined` for a DOMString data source?

I feel necessary as I always prefer tight checks, thus users passing 'utf-16' for a DOMString will not get a wrong understanding that the DOMString is successfully encoded as 'utf-16' and written into the nfc tag finally.

The context is https://chromium-review.googlesource.com/c/chromium/src/+/1991972/1/third_party/blink/renderer/modules/nfc/ndef_record.cc#153
