### ISSUE TITLE
cancelPush() should have target ?

### ISSUE THREAD

**Issue by riju** [w3c-cg/web-nfc#54]
At any moment, there can be a maximum of 2 pushMessage() for an adapter, 1 for tag, 1 for peer.
So correspondingly 2 messageBuffer/NFCMessage, 2 timers, etc. 
Presently in cancelPush(), all the instances of pushMessage() are invalidated. 
Do you want to add "target" as a parameter to cancelPush() ?

**Comment by kenchris** [comment]
I think it is fine that it cancels everything for now. Cancelable Promises are on their way and we would want to migrate to using that when that happens (unless that is way in the future).

**Comment by zolkis** [comment]
Until cancellable Promises come, we should add a target to cancelPush(). This would also be in line with having 2 separate timers, outboxes, and instances of the algo allowed.

**Comment by zolkis** [comment]
Working on it now.

**Comment by kenchris** [comment]
Please add a NOTE about this probably going away in the future

**Comment by kenchris** [comment]
btw, some experimentation from domenic https://github.com/domenic/cancelable-promise/blob/master/test/cancelable-promise.js

**Comment by zolkis** [comment]
#50 fixes this.
