### ISSUE TITLE
Provide TypeScript Declaration File for Web NFC

### ISSUE THREAD

**Issue by beaufortfrancois** [w3c-cg/web-nfc#540]
I'm sure TypeScript developers would appreciate if they'd had a `d.ts` file. 

For info, https://github.com/takefumi-yoshii/webnfc-media-memo/blob/master/src/types/global.ts  already exists.

**Comment by kenchris** [comment]
Makes sense to have as part of this repo. I totally agree! @takefumi-yoshii do you mind contributing it to this repo?

**Comment by takefumi-yoshii** [comment]
@beaufortfrancois @kenchris Of course! I'll contribute as soon as possible 😄

**Comment by beaufortfrancois** [comment]
https://github.com/w3c/web-nfc/blob/gh-pages/web-nfc.d.ts is part of the repo. I'll close this issue.
