### ISSUE TITLE
Get rid of filtering

### ISSUE THREAD

**Issue by kenchris** [w3c-cg/web-nfc#560]
It turns out that filtering was not the greatest idea

* it is a bit confusing as it is not filtering the records (not sure that would actually be that useful without complex rules) and it just filters whether such a record exist 
* Newer standards like TNEP have other ways of selecting services as a way of filtering/communicating with IoT devices.

So let's get rid of it and simplify spec and implementation. @zolkis

**Comment by beaufortfrancois** [comment]
I would split this issue in two: "Get rid of filtering" and "Get rid of AbortController".
Regarding the AbortController, can you share the TAG members notes?

**Comment by zolkis** [comment]
I agree with all the above.
@leonhsl are you fine with this?

**Comment by kenchris** [comment]
> I would split this issue in two: "Get rid of filtering" and "Get rid of AbortController".
> Regarding the AbortController, can you share the TAG members notes?

https://github.com/w3c/web-nfc/issues/562

We didn't minute that, but I am assigned to add that policy to our design policy document but haven't gotten around to it yet

**Comment by kenchris** [comment]
Leave open until merged to spec

**Comment by kenchris** [comment]
Done on branch: https://github.com/w3c/web-nfc/commit/c6eaae294626ab2f59276d54367b83094b57a6ff

**Comment by kenchris** [comment]
Looking through the code, I don't see any where the filtering is actually done, so it might be as easy to remove the 3 properties in the dictionary in the files below:

third_party/blink/web_tests/external/wpt/interfaces/web-nfc.idl
third_party/blink/renderer/modules/nfc/ndef_scan_options.idl

@zolkis is this handled in the spec?

![image](https://user-images.githubusercontent.com/1101339/82812700-dfc78f00-9e93-11ea-9bf5-8c1c2116a182.png)

**Comment by zolkis** [comment]
> @zolkis is this handled in the spec? 

In the draft branch, yes, by #565

**Comment by beaufortfrancois** [comment]
Filtering is done on the Java side:
https://source.chromium.org/chromium/chromium/src/+/master:services/device/nfc/android/java/src/org/chromium/device/nfc/NfcImpl.java;l=615;drc=cc291e324ffba9c0282d62f00c2005637d5fb37a?originalUrl=https:%2F%2Fcs.chromium.org%2F
https://source.chromium.org/chromium/chromium/src/+/master:services/device/nfc/android/java/src/org/chromium/device/nfc/NfcImpl.java;l=597;drc=7f2a66319b71e1cd3be556aeaa50cd18d1be70c1?originalUrl=https:%2F%2Fcs.chromium.org%2F

**Comment by kenchris** [comment]
I see, seems easy to remove though, so that is good!

**Comment by kenchris** [comment]
This has been integrated into the spec
