### ISSUE TITLE
Join Reader and Writer objects

### ISSUE THREAD

**Issue by kenchris** [w3c-cg/web-nfc#561]
I take the blame for this. It originally seemed like a good idea with separate objects, but I am getting more and more convinced that it was a bad idea.

* If we enhance to be able to select tag in the case of multiple tags read, this is required
* TNEP also requires this
* We can get rid of ignoreRead
* User is more in control of what happens.

Suggested name `NDEFPoller` or `NDEFPollerDevice`

**Comment by OlivierGrenoble** [comment]
> If we enhance to be able to select tag in the case of multiple tags read, this is required

On Android, it is not possible to select one tag among several tags. There should be only one in the RF field.

**Comment by reillyeon** [comment]
I vote for calling the combined object `NDEFReader`. The physical hardware components for NFC seem to usually be called a "reader" even though they can also write. It doesn't seem necessary to find a new (potentially awkward) word to describe it.

**Comment by kenchris** [comment]
I need to get hand on the new NFC TNEP spec, but it looks like they used poller device (vs tag device) but I need to confirm

**Comment by OlivierGrenoble** [comment]
> I vote for calling the combined object `NDEFReader`. The physical hardware components for NFC seem to usually be called a "reader" even though they can also write. It doesn't seem necessary to find a new (potentially awkward) word to describe it.

I agree

**Comment by kenchris** [comment]
I checked the new spec and it seems that the Poller thing was just what Nordic named it in their API.

> Currently the following NFC Forum Devices are defined:
>  * NFC Universal Device
>  * NFC Tag Device
>  * NFC Reader Device.

**Comment by zolkis** [comment]
> I vote for calling the combined object NDEFReader

> Currently the following NFC Forum Devices are defined:
NFC Universal Device
NFC Tag Device
NFC Reader Device

Ergo what about `NFCReader`, bearing in mind possible future support for NDEF+other tech for a given device? 

**Edit.** 
In fact, pondering whether `NFCDevice` or `NDEFDevice` would be better. Think about e.g. [Example 2](https://w3c.github.io/web-nfc/#example-2).

```javascript
const writer = new NDEFWriter();
writer.write(
  "Hello World"
).then(() => {
  console.log("Message written.");
}).catch(error => {
  console.log(`Write failed :-( try again: ${error}.`);
});
```
 If we used `NDEFReader`, we created  `reader` and use it for writing.

```javascript
const reader = new NDEFReader();
reader.write(
  "Hello World"
).then(() => {
  console.log("Message written.");
}).catch(error => {
  console.log(`Write failed :-( try again: ${error}.`);
});
```
I know we could call it `const ndef = new NDEFReader();` as well, but maybe would look better this way:

```javascript
const ndef = new NFCDevice();
ndef.write(
  "Hello World"
).then(() => {
  console.log("Message written.");
}).catch(error => {
  console.log(`Write failed :-( try again: ${error}.`);
});
```

**Comment by reillyeon** [comment]
I'd be cautious about assuming that the existing API can be extended to support future technologies. Keeping the API focused on NDEF allows us to only consider a subset of all possible NFC interactions and built the best API for that.

**Comment by zolkis** [comment]
Discussed with Kenneth that we'd likely stick with `NDEFReader` that will have a `write()` method :).

**Comment by kenchris** [comment]
Fixed on branch: https://github.com/w3c/web-nfc/commit/00509fc2df1fa63a0456034afb04eb16d03ca4cd

**Comment by kenchris** [comment]
Merged upstream
