### ISSUE TITLE
Throw NotSupportedError (or similar) when NFC isn't supported

### ISSUE THREAD

**Issue by kenchris** [w3c-cg/web-nfc#576]

**Comment by beaufortfrancois** [comment]
This is a Chromium implementation issue, not spec related.
In Chrome, the `NDEFReader` interface won't be exposed at all if the API is not supported (Desktop platform for now) to avoid potential confusion.

**Comment by beaufortfrancois** [comment]
With my previous comment, I believe we can close this issue. Please re-open if I'm wrong.
