### ISSUE TITLE
Remove ignoreRead and add examples of how to easy accomplish

### ISSUE THREAD

**Issue by kenchris** [w3c-cg/web-nfc#579]
Done on branch: https://github.com/w3c/web-nfc/commit/00509fc2df1fa63a0456034afb04eb16d03ca4cd

**Comment by kenchris** [comment]
Approx code that would have to be removed

https://source.chromium.org/search?q=ignoreRead()&sq=&ss=chromium%2Fchromium%2Fsrc:third_party%2Fblink%2F&originalUrl=https:%2F%2Fcs.chromium.org%2F

**Comment by beaufortfrancois** [comment]
https://source.chromium.org/search?q=ignoreRead%7Cignore_read%20f:nfc%20-f:debug&originalUrl=https:%2F%2Fcs.chromium.org%2F covers a bit more.

**Comment by kenchris** [comment]
Yay, you are better at searching than I am :-)

**Comment by kenchris** [comment]
This has happened
