### ISSUE TITLE
Make sure Ack section is up to date

### ISSUE THREAD

**Issue by kenchris** [w3c-cg/web-nfc#581]
Balasz Engeni, Reilly are at least missing. More might be!

**Comment by riju** [comment]
Balazs Engedy

**Comment by beaufortfrancois** [comment]
Theodore Olsauskas-Warren and Balazs Engedy both would love to be in the Ack section as their help definitely improved the spec regarding security and privacy.

**Comment by zolkis** [comment]
What about Reilly? At least I am really grateful for his informed and concise suggestions.

**Comment by kenchris** [comment]
> What about Reilly? At least I am really grateful for his informed and concise suggestions.

![image](https://user-images.githubusercontent.com/1101339/82929440-ef260580-9f83-11ea-8f91-af70c0b4637a.png)

**Comment by kenchris** [comment]
Want to do the PR @zolkis?
