### ISSUE TITLE
Web NFC available on Chrome 84?

### ISSUE THREAD

**Issue by Fortuntato** [w3c-cg/web-nfc#589]
Hi all, as we are approaching the date when Chrome v.84 will be released I was wondering if this feature is going to be released or not because, long story short, I have made my University dissertation about this feature and I have produced a Web App with NFC. 
Once I complete it I would be more than happy to share my research with you. But for the moment I really need to know what happens on the 14th July when the new version of Chrome is released because that is a crucial date for me if something changes.

**Comment by riju** [comment]
@Fortuntato : As you might be aware, we did run Origin Trials and we got a few feedback from developers. We are addressing those them right now.

**Comment by Fortuntato** [comment]
@riju Thank you for the reply. So for the time being until the end of the month, the feature will be still available as part of the Experimental Web Features flag on Chrome?

**Comment by beaufortfrancois** [comment]
Yes. The flag will still be available in Chrome.

**Comment by anssiko** [comment]
@Fortuntato I'm excited to hear you chose Web NFC as your dissertation topic. Please contribute your findings to the group when you're ready to do so. Also, I encourage you to [join the group](https://www.w3.org/community/web-nfc/) to keep in touch even after you're done with your dissertation. Maybe you'll be using this technology in your future projects.

I'll close this issue now. Please chime in if you have any further questions.

**Comment by Fortuntato** [comment]
Hi all! I have finalised my software project and dissertation/report about it. This is my project repository: https://github.com/Fortuntato/Contactless-Voucher
A copy of the project report can be downloaded here: https://www.dropbox.com/s/xk33znh06bj4tps/Contactless%20Loyalty%20Project%20Report.pdf?dl=0
