### ISSUE TITLE
TAG review

### ISSUE THREAD

**Issue by anssiko** [w3c-cg/web-nfc#60]
We should distill the W3C TAG review feedback when available (see the [Web NFC API w3ctag/spec-reviews issue](https://github.com/w3ctag/spec-reviews/issues/22#issuecomment-140744005)).

**Comment by anssiko** [comment]
A work-in-progress draft [W3C TAG review feedback on NFC API](https://github.com/w3ctag/spec-reviews/blob/master/2015/10/nfc-feedback.md) from @travisleithead of TAG (thanks!).

I suggest we distill this (still evolving) feedback at our joint [Web Bluetooth and Web NFC F2F meeting](https://www.w3.org/wiki/TPAC/2015/ad-hoc-meetings#Web_Bluetooth_and_Web_NFC) at TPAC.

@travisleithead you're welcome to pop in at our TPAC F2F meeting if you have time on Monday Oct 26 between 15:00-18:00. Room 201, 2F in Sapporo Convention Center, see the [meeting wiki page](https://www.w3.org/wiki/TPAC/2015/ad-hoc-meetings#Web_Bluetooth_and_Web_NFC) for further pointers.

**Comment by kenchris** [comment]
We have added individual issues for the issues which were found in the TAG review and other which came up at TPAC.

OK to close this one @anssiko ?

**Comment by anssiko** [comment]
I'll close this meta issue, since the TAG review feedback has now been split into [specific issues labeled with "TAG feedback"](https://github.com/w3c/web-nfc/labels/TAG%20feedback) that was discussed at F2F (also the [respective issue in w3ctag/spec-reviews](https://github.com/w3ctag/spec-reviews/issues/22#issuecomment-140744005) has been closed).

The specific "TAG feedback" issues are to be referenced in commits that address them to ease tracking.
