### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by dbwodlf3** [w3c-cg/web-nfc#603]
https://w3c.github.io/web-nfc/#the-ndef-record-and-fields

there are written "bytes". but there are really not bytes. just bits.

Only the first three bytes (lines in figure) are mandatory. => Only the first three bits

**Comment by beaufortfrancois** [comment]
I believe "Bytes" refer to the lines. Each line is a byte, which consists of 8 bits (rows).
@kenchris Do you confirm?

**Comment by kenchris** [comment]
correct

**Comment by dbwodlf3** [comment]
ah.. understand.
