### ISSUE TITLE
Lock NFC tag

### ISSUE THREAD

**Issue by MohammadR-prog** [w3c-cg/web-nfc#618]
Hi.
is there any way to lock nfc tag with password using js and chrome android?

**Comment by lyellick** [comment]
> Hi.
> is there any way to lock nfc tag with password using js and chrome android?

You could always keep track of that nfc serial number and keep it's contents within a database where you only show it if the password is given. Nothing out of the box would support this and would need to be custom. This isn't an issue with the backend so I'm sure this will be closed as an non issue.

**Comment by kenchris** [comment]
That is not part of the underlying NDEF standard, but you can always encrypt the data you store
