### ISSUE TITLE
Cancel Scan()

### ISSUE THREAD

**Issue by sc-rf** [w3c-cg/web-nfc#619]
I am working on intercepting the nfc data in a Reactjs (typescript) App, but when i change the route the Scanner still intercepting the NFC tag (and i want it to cancel the Listener when i change the page)

**Comment by lyellick** [comment]
Can you show how you are initializing `NDEFReader()`? Also to be clear we aren't talking about `AbortController()`, right?

**Comment by beaufortfrancois** [comment]
@sc-rf Does https://web.dev/nfc/#abort-nfc-operations help?

**Comment by kenchris** [comment]
This is doable with AbortController
