### ISSUE TITLE
Heads up: refs to `pagevisibility` (external now visibile) about to be removed

### ISSUE THREAD

**Issue by noamr** [w3c-cg/web-nfc#626]
See w3c/page-visibility#73
Most of the page visibility spec is moving into the HTML Spec (see whatwg/html#7153), and calls are to be made explicitly instead of the "hook" (external-now-visible-algorithm).

Since this spec appears to rely on this ref, opening this issue to track switching to being called directly.

**Comment by beaufortfrancois** [comment]
Do you have examples of other specs that have switched to the HTML spec for page visibility?

**Comment by noamr** [comment]
> Do you have examples of other specs that have switched to the HTML spec for page visibility?

Not yet
It's all quite new
I can assist with advice if someone starts a PR etc

**Comment by yoavweiss** [comment]
It might be worthwhile to create a helper algorithm inside HTML that would enable specs that want to add processing when the page is hidden/visible to do that more easily (without mucking around with history traversal).

**Comment by noamr** [comment]
> It might be worthwhile to create a helper algorithm inside HTML that would enable specs that want to add processing when the page is hidden/visible to do that more easily (without mucking around with history traversal).

I think if I add that algorithm I might as well add the 3 calls to the other specs

**Comment by noamr** [comment]
See https://github.com/whatwg/html/pull/7238

**Comment by noamr** [comment]
https://html.spec.whatwg.org/#page-visibility-change-steps

**Comment by beaufortfrancois** [comment]
Thank you @noamr!
See https://github.com/w3c/web-nfc/pull/627
