### ISSUE TITLE
Update "aborted flag" references and use "abort reason" instead

### ISSUE THREAD

**Issue by miketaylr** [w3c-cg/web-nfc#630]
In whatwg/dom#1027, the "aborted flag" was removed. There's guidance on how to reject with abort reason instead, in https://dom.spec.whatwg.org/#abortcontroller-api-integration.

**Comment by beaufortfrancois** [comment]
Thank you @miketaylr for raising this!
I've started a PR at https://github.com/w3c/web-nfc/pull/631 to address this. Let me know what you think.
