### ISSUE TITLE
Consider using mediaType instead of type, type for kind

### ISSUE THREAD

**Issue by kenchris** [w3c-cg/web-nfc#65]
"The NFCRecord.type : this is the IANA media type, should jive with other uses of "mimeType" instead for clarity. NFCRecord.kind : this should likely be "type" instead."

https://github.com/w3ctag/spec-reviews/blob/master/2015/10/nfc-feedback.md

**Comment by zolkis** [comment]
I fully agree with this. 
Let `type` become `mediaType`, and  `kind` become `type`.

IMO we should not use `mimeType` any more, then `ianaMediaType` could just be shortened as `mediaType`.

**Comment by kenchris** [comment]
I am fine with this too

**Comment by zolkis** [comment]
I am implementing this change.

**Comment by riju** [comment]
:+1:

**Comment by zolkis** [comment]
Should `type` be `recordType` for added clarity?

Now it looks a bit weird to have both `type` and `mediaType` in the same dictionary.

**Comment by kenchris** [comment]
fine with me
