### ISSUE TITLE
Android WebView Permission

### ISSUE THREAD

**Issue by juliodiz** [w3c-cg/web-nfc#650]
Hello

I am trying to use to Android WebView for use at my APP. Its working perfectly at chrome but inside the APP shows the message has no permission.

"NotAlloewdError: NFC permission request denied"

Its possible to have Web NFC at Android WebView? Need to do something to work?

**Comment by beaufortfrancois** [comment]
Hey @juliodiz, Web NFC is not supported in Android Webview. It's mainly due to the fact that Chrome Web NFC shows a [prompt](https://web.dev/nfc/#security-and-permissions) in Chrome and prompts are not implemented in Android WebView.
