### ISSUE TITLE
Read NFC tag after writing to it

### ISSUE THREAD

**Issue by beaufortfrancois** [w3c-cg/web-nfc#654]
It is currently cumbersome to read records from an NFC tag after writing to it as the user must tap the NFC tag one first time to write to it, then make it out of range so that they can tap it again to read records.

To help with that journey, I was thinking we could perform a read NFC operation after a write NFC operation and return the `NDEFMessage` when the `NDEFReader.write()` promise resolves if web developers expressed it via an `NDEFWriteOptions` option.

```js
// Waiting for user to tap NFC tag...
const ndef = new NDEFReader();
await ndef.scan();

// Write and read NFC tag.
const message = await ndef.write("Hello world", { readAfter: true }); // <-- NEW!
console.log(message);
```

Note that by setting the `readAfter` default value to `false`, the current behavior does not change for existing web apps using `NDEFReader.write()` today.  

```webidl
interface NDEFReader : EventTarget {
  ...
  Promise<NDEFMessage?> write(NDEFMessageSource message,
                              optional NDEFWriteOptions options={});
};

partial dictionary NDEFWriteOptions {
  boolean readAfter = false;
};
```

**Comment by kenchris** [comment]
I am supportive of this

**Comment by zolkis** [comment]
+1 (why not)

Remind me, what was the use case? 
Convenience for single tap, when wanting to make sure the written content is the same as the one at hand when writing?

**Comment by beaufortfrancois** [comment]
This is actually not needed and can be exercised with the JavaScript code below. Sorry for the noise.

```js
// Waiting for user to tap NFC tag to write to it...
const ndef = new NDEFReader();
await ndef.write("Hello world");
// Success! Message has been written.

// Now scanning for 3 seconds...
const abortController = new AbortController();
await ndef.scan({ signal: abortController.signal });
const message = await new Promise((r) => {
  ndef.onreading = (e) => r(e.message);
});
// Success! Message has been read.

await new Promise((r) => setTimeout(r, 3000));
abortController.abort();
// Scanning is now stopped.
```

**Comment by kenchris** [comment]
Maybe it merits an example in the spec or in your article then?

**Comment by zolkis** [comment]
> This is actually not needed and can be exercised with the JavaScript code below. Sorry for the noise.
> // Waiting for user to tap NFC tag to write to it...
> // Now scanning for 3 seconds...
> // Scanning is now stopped.

So from the user perspective, the tag is just being held there for 3 seconds (or less, until read), and that solves the original issue, that a user was assumed to need to tap, lift, and tap again?

But would the second part still make sense for convenience? IIRC we used to have this: what was the reason for removing? Occam, or something more?

> I was thinking we could perform a read NFC operation after a write NFC operation and return the NDEFMessage when the NDEFReader.write() promise resolves if web developers expressed it via an NDEFWriteOptions option.

**Comment by beaufortfrancois** [comment]
> Maybe it merits an example in the spec or in your article then?

Good idea! See https://developer.chrome.com/articles/nfc/#read-after-write
