### ISSUE TITLE
Avoid using Adapter in API

### ISSUE THREAD

**Issue by kenchris** [w3c-cg/web-nfc#66]
https://github.com/w3ctag/spec-reviews/blob/master/2015/10/nfc-feedback.md

> ...avoid use of the word "Adapter" (which felt foreign to me). Suggestion: navigator.requestNFC() --- instead of navigator.nfc.requestAdapter()

**Comment by zolkis** [comment]
No strong opinion on this. Fine with `navigator.requestNFC()`.

However, we have to continue talking about the notion of Adapter in the spec, similarly Bluetooth will likely need to maintain the notion. Something to be discussed on the F2F.
