### ISSUE TITLE
Well known type T status bit 7

### ISSUE THREAD

**Issue by RobChaferDID** [w3c-cg/web-nfc#660]
In https://w3c.github.io/web-nfc/#text-record 

Regarding the status byte, it says

"If bit 7 if set, means the payload is encoded in UTF-8, otherwise in UTF-16."

Is this correct?  If I set bit 7 and followed by (single byte) Latin letters I get Chinese characters read by my phone (and TagInfo). If I reset bit 7 it reads as Latin characters.

**Comment by beaufortfrancois** [comment]
I think you're right, the WebNFC spec should be updated to reflect NFC spec:

![image](https://github.com/w3c/web-nfc/assets/634478/d958c801-afb3-4119-a418-78b6d35854f5)
 
FYI here's the [Chromium code](https://source.chromium.org/chromium/chromium/src/+/main:services/device/nfc/android/java/src/org/chromium/device/nfc/NdefMessageUtils.java;l=281;drc=71bd8f1596b301a842247d3488f901d7ae3dfad2):

```java
        // According to NFCForum-TS-RTD_Text_1.0 specification, section 3.2.1 Syntax.
        // First byte of the payload is status byte, defined in Table 3: Status Byte Encodings.
        // 0-5: lang code length
        // 6  : must be zero
        // 7  : 0 - text is in UTF-8 encoding, 1 - text is in UTF-16 encoding.
        nfcRecord.encoding = (text[0] & (1 << 7)) == 0 ? ENCODING_UTF8 : ENCODING_UTF16;
```

**Comment by beaufortfrancois** [comment]
I've opened https://github.com/w3c/web-nfc/pull/661 to fix this.

**Comment by RobChaferDID** [comment]
Excellent, I can stop worrying my writer was wrong :)
