### ISSUE TITLE
Avoid resemblance with postMessage

### ISSUE THREAD

**Issue by kenchris** [w3c-cg/web-nfc#68]
https://github.com/w3ctag/spec-reviews/blob/master/2015/10/nfc-feedback.md

> pushMessage reminds me of postMessage. Given there is little similarity, perhaps a rename to push (simpler, shorter, no resemblance to postMessage).

**Comment by zolkis** [comment]
Fine with `push()`.

Eventually we could also think of separating `push()` (to peers) from `write()` (to tags).

**Comment by zolkis** [comment]
Fixed by #88.
