### ISSUE TITLE
can pushMessage avoid pushing a sequence?

### ISSUE THREAD

**Issue by kenchris** [w3c-cg/web-nfc#69]
https://github.com/w3ctag/spec-reviews/blob/master/2015/10/nfc-feedback.md

> pushMessage is highly structured (sequence<NFCRecord>). Why is it pushing a list? Shouldn't it push just one thing at a time? Is the grouping significant to the protocol? Can this be abstracted away?

**Comment by zolkis** [comment]
This is coming from the structure of NDEF messages.

It cannot push one record at a time.

We could define an `NDEFMessage` structure for containing just the sequence, and then `WebNFCMessage` to be what [`NFCMessage`](https://w3c.github.io/web-nfc/#the-nfcmessage-dictionary) is now.
