### ISSUE TITLE
Should the NFCPushTarget dictionary member be required

### ISSUE THREAD

**Issue by kenchris** [w3c-cg/web-nfc#70]
https://github.com/w3ctag/spec-reviews/blob/master/2015/10/nfc-feedback.md

> NFCPushTarget -- given the format is the same, why is the push target ("peer" or "tag") a necessary thing? Should this dictionary member be required?

**Comment by zolkis** [comment]
Yes.

The alternative is to separate into 2 functions, see [this comment](https://github.com/w3c/web-nfc/issues/68#issuecomment-148345149) in #68.

**Comment by zolkis** [comment]
Or, we can reintroduce the value "any" and make it the default.

**Comment by zolkis** [comment]
Fixed by #88.
