### ISSUE TITLE
watch API should have the options dictionary as a second parameter

### ISSUE THREAD

**Issue by kenchris** [w3c-cg/web-nfc#71]
https://github.com/w3ctag/spec-reviews/blob/master/2015/10/nfc-feedback.md

> By convention, the watch API should have the options dictionary as a second parameter (not vice-versa). This will also allow the dictionary to be optional, which it is already setup for.

**Comment by kenchris** [comment]
Unfortunately that means that user code might "hide" the filtering, like

```
watch(function() {

  // long body.

}, filter)

```

**Comment by zolkis** [comment]
No strong opinion on this, either way works for me.
