### ISSUE TITLE
NFCWatchOptions improvements

### ISSUE THREAD

**Issue by kenchris** [w3c-cg/web-nfc#72]
https://github.com/w3ctag/spec-reviews/blob/master/2015/10/nfc-feedback.md

> NFCWatchOptions -- values are single strings. If filtering is desired, can multiple match options be possible (e.g., a variety of types or kinds?) If so, this should likely be an array of strings, e.g., like MutationObserverOptions:attributeFilter.

**Comment by zolkis** [comment]
It is already possible to register multiple filters per adapter, which act in OR.

IMO we don't need AND semantics here, therefore I would not do any change on the current design.
