### ISSUE TITLE
Are kind and type relevant in the filter

### ISSUE THREAD

**Issue by kenchris** [w3c-cg/web-nfc#75]
https://github.com/w3ctag/spec-reviews/blob/master/2015/10/nfc-feedback.md

> The filtering (in watch) seems hard to reason about as a web developer. How is one to know what to expect when starting to watch for messages, which message type/kind will be relevant unless there is already a relationship established with the other NFC party as to what NFC Record fields it will use. I'm not certain how relevant it is to expose these extra filtering options unless they are particularly relevant.

**Comment by zolkis** [comment]
They may be relevant from the use case point of view: let's say that I as a web solution developer use a certain type of Web NFC tags, and I am not interested in getting callbacks from any other reads.
I think this has a good chance to be relevant.
