### ISSUE TITLE
Clamp NFCPushOptions.timeout and provide default values

### ISSUE THREAD

**Issue by alexshalamov** [w3c-cg/web-nfc#81]
If NFCPushOptions.timeout can be set to Infinity, it should be clamped.

It will be also nice to have default values set for: 
NFCPushOptions.timeout to "0xFFFFFFFF max timeout"
NFCPushOptions.target to "tag" enumeration value

``` javascript
dictionary NFCPushOptions {
    NFCPushTarget target = "tag";
    [Clamp] unsigned long timeout = 0xFFFFFFFF;
};
```

**Comment by kenchris** [comment]
Why not just write a note that the UA might clamp to a UA specific upper bound?

**Comment by riju** [comment]
Its ok to be explicit in the idl, geolocaltion, vibration, etc do it.

**Comment by alexshalamov** [comment]
@zolkis 
http://www.ecma-international.org/ecma-262/5.1/#sec-8.5
http://www.w3.org/TR/WebIDL/#es-unsigned-long
If x > 2^32 − 1, then throw a TypeError

I wonder why other specs (MSE, WebAudio, Battery, DeviceLight) use "unrestricted double" for Infinity values? Should we also use:

``` javascript
dictionary NFCPushOptions {
    NFCPushTarget target = "any";
    unrestricted double timeout; // default value +Infinity
};
```

**Comment by zolkis** [comment]
Could we use `unsigned long long` and say the value 0 means no timer (i.e. timeout=`Infinity`)?
That would be in line with step 4 of http://www.w3.org/TR/WebIDL/#es-unsigned-long-long.

**Comment by kenchris** [comment]
@anssiko your input please? :)

**Comment by alexshalamov** [comment]
timeout: 0; means 0 ms, timer will be created and push operation would be cancelled in 0 ms.

I have to represent "infinity" value somehow in implementation, at the moment I use "unrestricted double timeout;" in the idl, which is mapped to "double".

``` javascript
std::numeric_limits<double>::has_infinity => true
std::numeric_limits<unsigned long long>::has_infinity => false
std::numeric_limits<unsigned long>::has_infinity => false
```

**Comment by zolkis** [comment]
OK, that solves it. Thanks.
