### ISSUE TITLE
Add method for clearing all watches?

### ISSUE THREAD

**Issue by zolkis** [w3c-cg/web-nfc#85]
From @alexshalamov: should we provide way to clear all watches? 

If developer is "sloppy" and don't save watch ids, should we provide way to clear _all_ watches?
Would developers use it more than single `clearWatch()`? Or wait until a clear need arises?

Or just make parameter optional, and if no id provided to `clearWatch()`, then clear all watches?

**Comment by kenchris** [comment]
cancelAllWatches() should suffice for now, until we get `CancellablePromise`s, and still make sense when we do. Similar to #86

**Comment by zolkis** [comment]
Fixed by #88.
